### ISSUE TITLE
Functions of numeric type and support for dark mode of tag type

### ISSUE THREAD

**Issue by daoif** [trey-wallis/obsidian-notion-like-tables#101]
This is a great form plug-in
1.  I hope to support simple arithmetic functions in number types, such as = sub() in Excel

2.  tag type please consider supporting dark mode.  
Dark mode: the current tag can't see the text clearly when selecting the color

**Comment by trey-wallis** [comment]
@daoif Hi daoif. Thank you for your feature requests. Arithmetic functions seem interesting. Could you give me some specific examples of functions with input and output? e.g.  text: add(1,2) rendered output: 3

Yes, that is something I have noticed about dark mode. I will be able to fix that.

**Comment by daoif** [comment]
@trey-wallis 
![image](https://user-images.githubusercontent.com/46199660/166132714-24cfc3f5-ded3-469b-b584-98e67e59c2da.png)
I mean the operation between cells, like the sub () of Excel
