### ISSUE TITLE
 date cell type and arithmetic functions

### ISSUE THREAD

**Issue by aflyker** [trey-wallis/obsidian-notion-like-tables#108]
hi, this plugin is great; I have a few suggestions:
1. add a cell type for date that can be selected in a calendar.
2. Add arithmetic functions like addition or multiplication in the cells.
thanks for the plugin!

**Comment by trey-wallis** [comment]
@aflyker Hi Alfyker. Thanks for your suggestions! 

1. I am planning on adding this as my next date type.
2. Could you give me some examples? This seems similar to #101

**Comment by trey-wallis** [comment]
@aflyker Dates added in 3.1.0. Check it out! :)

**Comment by aflyker** [comment]
hi, thanks for the new update; And about the arithmetic functions, I thought about whether addition, subtraction, multiplication and division operations could be included between the cells of the table... as in spreadsheets.

**Comment by Stilts15ak** [comment]
In the date type on the current release, you are only able to input a date 6 months in the past of the current date and 1 year in the future of the current date. Is this by design or a bug?

**Comment by trey-wallis** [comment]
@Stilts15ak It was a bug. Fixed in 3.5.2

**Comment by Stilts15ak** [comment]
Works great! Thank you!

**Comment by bagameow** [comment]
Basic functions like sum, average, max, min, count will be very useful!

**Comment by trey-wallis** [comment]
@bagameow Will add to the roadmap. Thanks :)

**Comment by trey-wallis** [comment]
@bagameow @aflyker Added arithmetic functions in 6.4.0
