### ISSUE TITLE
[BUG] Links that start with "&" automatically generate "amp;" with every reloading of the table

### ISSUE THREAD

**Issue by foxxxyfoxxx** [trey-wallis/obsidian-notion-like-tables#113]
**Describe the bug**
When a link start with "&" every time the table updates "amp;" is added to the link making it unusable. 
 
**To Reproduce**

1. Create table
2. Add link with "&" at the beginning of the link e.g. [[& Example Link]]
3. Click on another cell to update the table
4. The link should now turn into [[&amp; Example Link]]
5. Another click / table update should add another "amp;" turning the example into :: [[&amp;amp; Example Link]]
6. This process can be repeated endlessly.

**Expected behavior**
No "amp;" should be added to any links. The links should stay intact without any changes.

**Screenshots**
<img width="269" alt="image" src="https://user-images.githubusercontent.com/49116853/166133795-cb49d8af-a767-48a9-a3d8-bcb548a03aa8.png">

**Debug Info**
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Windows 10 Home 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 58
	Plugins enabled: 47
		1: Templater
		2: Sliding Panes (Andy's Mode)
		3: Typewriter Scroll
		4: Outliner
		5: Style Settings
		6: Hider
		7: Workspaces Plus
		8: AidenLx's Folder Note
		9: Folder Note Core
		10: Sortable
		11: Excalidraw
		12: Minimal Theme Settings
		13: Remember cursor position
		14: Calendar
		15: Control Characters
		16: Cycle through Panes
		17: Dataview
		18: Format Hotkeys
		19: Hotkeys++
		20: koncham workspace
		21: Longform
		22: Maximise Active Pane
		23: Natural Language Dates
		24: Note Refactor
		25: Autocomplete
		26: Day Planner
		27: Emoji Toolbar
		28: Excel to Markdown Table
		29: Hover Editor
		30: JiraIssue
		31: Kanban
		32: Mind Map
		33: Pandoc Plugin
		34: Sentence Navigator
		35: Hotkeys for starred files and searches
		36: Smarter Markdown Hotkeys
		37: Tasks
		38: Obsidian42 - Text Transporter
		39: Pane Relief
		40: QuickAdd
		41: Recent Files
		42: Settings Search
		43: Advanced Tables
		44: Tag Wrangler
		45: Text Snippets
		46: Various Complements
		47: Notion-Like Tables

**Using Mobile App?**
No

**Comment by trey-wallis** [comment]
Hi @foxxxyfoxxx. Thank you for your bug report. Yes, this seems like what should be happening with how things are coded right now. I can take a look into fixing this.

**Comment by trey-wallis** [comment]
@foxxxyfoxxx Fixed in 3.3.1. Check it out! :)

**Comment by foxxxyfoxxx** [comment]
Hey, @trey-wallis , just tried it out and works like a charm! Thanks so much! :-)
