### ISSUE TITLE
Can I add images to the cells?

### ISSUE THREAD

**Issue by ccjcan** [trey-wallis/obsidian-notion-like-tables#114]
Any chance we could display image (from URL) in the cells?

**Comment by XuanNui** [comment]
I ALSO WANT  THIS PICTURE IN CELL

**Comment by trey-wallis** [comment]
@ccjcan Hi ccjan. Thank you for your feature request. This seems doable.

**Comment by ccjcan** [comment]
Hi, is it possible to add images to cells? Using <Img ….

**Comment by trey-wallis** [comment]
Added in 6.0.0
