### ISSUE TITLE
Trim columns

### ISSUE THREAD

**Issue by mk-uc** [trey-wallis/obsidian-notion-like-tables#126]
I know that at least minimal theme has an option to trim dataview table columns so that each cell isn't extremely wide. I have a large database and would love the ability to see just one line of text per cell (even if it's cut off) so that I can see more rows without having to scroll down.

**Comment by trey-wallis** [comment]
@mk-uc Hi mk-uc. Thank you for your feature request. If I'm understanding you correctly, you would like text to cut off, or have it show with ellipsis?

For example..

`This is a paragra....` And then maybe you could hover over it to see the full text?

**Comment by mk-uc** [comment]
Hi, yes! that's exactly right. The real point is so that rows can be much more compact. Databases in Notion are *much* easier to view and manage because of how compact everything is.

**Comment by trey-wallis** [comment]
Added trimming of number cells, date cells, and tag cells in 3.5.1. Will continue to work on this.

**Comment by trey-wallis** [comment]
@mk-uc I have added a new feature called `Wrap Overflow` in 4.1.0. Please check it out! :) I plan on adding a hover to the ellipsis.
