### ISSUE TITLE
Line breaks in a cell

### ISSUE THREAD

**Issue by laphylee** [trey-wallis/obsidian-notion-like-tables#128]
The native Obsidian table support line breaks in a cell: "adding a `<br>`". [Markdown Syntax - Obsidian Hub - Obsidian Publish](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/Markdown+Syntax)

Seems that NLT doesn't render `<br>`. Could you help  to support that? Or is there another approach to support a line break?

**Comment by trey-wallis** [comment]
Hi @laphylee. Yes, I think supporting <br/> tags would be fine. Other options would be to support some type of a custom line break that is inserted on key stroke, although for that could also just have break tags inserted as well. There is still a lot for me to potentially implement. I am only one developer and I don't use all the features of Obsidian, so any suggestions are very helpful! I will implement this in the next release.

**Comment by trey-wallis** [comment]
@laphylee Apparently markdown line breaks do not include a slash `<br>`. I will be changing them to use this format in 3.3.2.
