### ISSUE TITLE
Muli tag support 

### ISSUE THREAD

**Issue by hazemk537** [trey-wallis/obsidian-notion-like-tables#131]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trey-wallis** [comment]
@hazemk537 Hi Hazem. Thank you for your feature request. It you wouldn't mind, please edit the body of your request with relevant information regarding what you would like with multi-tag support. It might be self-explanatory, but it would also help me if you have any specific details. Thanks, Trey.

**Comment by trey-wallis** [comment]
@hazemk537 I plan on adding multi-tag support by the end of this week

**Comment by hazemk537** [comment]
Perfect 💓

**Comment by trey-wallis** [comment]
@hazemk537 Released in v5.0.0. Please check it out! :)
