### ISSUE TITLE
[BUG] I can't apply already created tags

### ISSUE THREAD

**Issue by javiavid** [trey-wallis/obsidian-notion-like-tables#140]
**Describe the bug**
When trying to use an already created tag, the cell stays in the same state.
This happens with empty cells or with cells that already have a tag

**To Reproduce**
-Create a table with 2 columns and 2 rows
-In the second column you change the data type to tag
-You write in the first cell a tag
-You click on the second cell (in the same column) to try to apply the same tag

**Expected behavior**
That the new cell has that tag

**Screenshots**
https://user-images.githubusercontent.com/7627504/168466071-151a2006-7194-40f1-a1fc-9cd2451ebd39.mp4

**Debug Info**
SYSTEM INFO:
	Obsidian version: v0.14.10
	Installer version: v0.14.5
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 2
	Safe mode: off
	Plugins installed: 16
	Plugins enabled: 1
		1: Notion-Like Tables

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Using Mobile App?**
no

**Comment by trey-wallis** [comment]
@javiavid Hi javiavid. I actually just discovered this bug. I will be pushing out a fix with the ability to change tags shortly. Thank you :)

**Comment by trey-wallis** [comment]
@javiavid Fixed in 3.2.0
