### ISSUE TITLE
[BUG]: can't select cell with checkbox using tab

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#141]
**Describe the bug**
can't select cell with checkbox using tab

**To Reproduce**
1. create table with checkbox
2. press tab until you select checkbox column

**Expected behavior**
highlight cell with checkbox

**Screenshots**

https://user-images.githubusercontent.com/38974541/168638710-37dcf008-a862-4287-aa8d-200defde5621.mov

**Debug Info**
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.5
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 27
	Safe mode: off
	Plugins installed: 56
	Plugins enabled: 42
		1: Divide & Conquer
		2: Dataview
		3: Advanced URI
		4: Auto Link Title
		5: Buttons
		6: Collapse All
		7: Creases
		8: Customizable Page Header and Title Bar
		9: Dynamic Table of Contents
		10: Force note view mode
		11: Global Hotkeys
		12: Media Extended
		13: MetaEdit
		14: MySnippets
		15: Natural Language Dates
		16: Number Headings
		17: Obsidian42 - BRAT
		18: Outliner
		19: Pane Relief
		20: QuickAdd
		21: Reminder
		22: Set Mobile Theme
		23: Settings Search
		24: Shell commands
		25: Smart Typography
		26: Style Settings
		27: System Dark Mode
		28: Tabout
		29: Task Collector (TC)
		30: Tasks
		31: Templater
		32: Garble Text
		33: Plugin Changelogs
		34: Hotkey Helper
		35: Archiver
		36: DB Folder
		37: Notion-Like Tables
		38: Packrat
		39: Linter
		40: Smarter Markdown Hotkeys
		41: Nuke Orphans
		42: Supercharged Links

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Using Mobile App?**
no

**Comment by trey-wallis** [comment]
I am going to disable this for right now. Since I am upgrading different components, will add back soon though.

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
