### ISSUE TITLE
header menu doesn't reset

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#142]
**Is your feature request related to a problem? Please describe.**
the header menu doesn't reset when clicking away from it

**Describe the solution you'd like**
the header menu resets when clicking away from it

**Describe alternatives you've considered**
manually press the back button each time

**Additional context**

https://user-images.githubusercontent.com/38974541/168639768-d15bc0b4-bd05-4c15-8bfe-94706cc3ad4a.mov

**Comment by trey-wallis** [comment]
Fixed in 3.2.0
