### ISSUE TITLE
modified and created time columns

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#143]
**Is your feature request related to a problem? Please describe.**
Sometimes, I want to sort the rows by modified time and created time, just like notion.

**Describe the solution you'd like**
add new type columns : 
1. modified time
2. created time

**Describe alternatives you've considered**
manually modifying a date.

**Additional context**
![Screen Shot 2022-05-16 at 5 32 27 PM](https://user-images.githubusercontent.com/38974541/168640643-c72bef4c-4869-4b19-b719-96e95157b4b0.jpg)

**Comment by trey-wallis** [comment]
Do you want these columns potentially visible or would it just be for sorting? Sorting by "default" right now sorts by the order that the rows were inserted

**Comment by imeed166** [comment]
Mainly for sorting yes, didn't know about the default sorting.

**Comment by trey-wallis** [comment]
Added in 6.0.0
