### ISSUE TITLE
delete column in main menu

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#144]
**Is your feature request related to a problem? Please describe.**
It's an extra step to click on the `edit` header menu, then the `delete` button.

**Describe the solution you'd like**
I think (just like notion), the delete button should be in the main header menu.

**Describe alternatives you've considered**
click on edit menu then delete every time.

**Additional context**
![image](https://user-images.githubusercontent.com/38974541/168641498-155eff53-1063-4f60-adf4-db9e9c651c76.png)

**Comment by trey-wallis** [comment]
@imeed166 I am a little hesitant with this because I wouldn't want users accidentally miss-clicking and deleting their row. Notion has a popup that asks you if you're sure you want to delete the row. That is 2 clicks as well.

**Comment by imeed166** [comment]
Ah okay, I understand
