### ISSUE TITLE
highlight cell instead of making it bigger when editing

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#145]
**Is your feature request related to a problem? Please describe.**
I can't select the cell below the one I'm editing due to the big prompt

https://user-images.githubusercontent.com/38974541/168641962-df97efaa-c3e0-4c47-85b4-a147db4f2dd6.mov

**Describe the solution you'd like**
highlight the cell instead of increasing its size (just like notion simple tables)

https://user-images.githubusercontent.com/38974541/168642295-b6698a7b-c215-4117-9f53-e0d11b570f98.mov

**Describe alternatives you've considered**
select the cell after clicking away from current one

**Comment by imeed166** [comment]
If this feature is implemented, It would make sense to add the ability to move around from one cell to another via the arrow keys.

**Comment by trey-wallis** [comment]
Oh it seems like Notion seems the textarea the size of the cell that is being edited and then resizes the actual cell at the time you are typing.

**Comment by trey-wallis** [comment]
Yes, moving around with keys would be good. This is a rather big update. I will need to place it on a lower priority for right now. I would like to get live preview working.

**Comment by trey-wallis** [comment]
@imeed166 I am REAL late on this but I plan on adding this in v5.1.0. Please check out v5.0.0. Thank you for all your feedback.

**Comment by imeed166** [comment]
No worries, the 5.0.0 update is really nice, it feels much more stable and refined than before. Looking forward to 5.1.0.
