### ISSUE TITLE
add button to reset data when invalid

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#146]
**Is your feature request related to a problem? Please describe.**
When the data in invalid, I have to switch back to editing view and delete the cell content

**Describe the solution you'd like**
add a button to reset the data if it's invalid, or make it reset automatically 

**Describe alternatives you've considered**
switch back to editing view and delete cell content

**Comment by trey-wallis** [comment]
Yes, this is a system that I implemented on the first release. I think a good solution might be just to allow the user to edit the invalid value in the table. No button would be necessary then. Thanks for bringing this up. This is something that should be relatively easy and I can push out an update by the end of the week.

**Comment by trey-wallis** [comment]
@imeed166 Fixed in 4.3.1! :)
