### ISSUE TITLE
Controlling Cell Width

### ISSUE THREAD

**Issue by kerrywoolnough** [trey-wallis/obsidian-notion-like-tables#151]
There appears to be a limit of ~17 characters (at least with my setup) on the extent to which columns can be narrowed. This causes columns with little content to take up an unnecessary amount of space on the page.

Example:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/73186440/168858936-c317e43a-c28a-4b16-8fa1-8a233bbd27d2.png">

I'm unsure of whether this is a bug, but it would be great if columns could be set to narrower widths.

**Comment by trey-wallis** [comment]
@kerrywoolnough Thank you for your issue. That's interesting. The min-width should be 100px. Are you able to resize the columns outward?

**Comment by kerrywoolnough** [comment]
Yes, I am able to resize the columns outward (extensively)

**Comment by trey-wallis** [comment]
<img width="331" alt="Screenshot at May 17 10-24-09" src="https://user-images.githubusercontent.com/40307803/168861021-3b6fe8e6-0068-4165-87ea-ed23fc7a7358.png">

If you add a new table, does it look like this?

**Comment by kerrywoolnough** [comment]
Upon creating a new table:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/73186440/168862538-71791b54-dc1b-4d33-a18a-950cda5d25b2.png">

Debug info:

SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 20.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Ebullientworks
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: obsidian markmind
		2: Notion-Like Tables
		3: Excel to Markdown Table

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.


Interestingly, I experience the same issue when using the Default theme.

**Comment by trey-wallis** [comment]
That is interesting! Could you send a screenshot of a new table with the default theme? It seems like with `Ebullientworks` the font size is very small

**Comment by kerrywoolnough** [comment]
Sure.
<img width="219" alt="image" src="https://user-images.githubusercontent.com/73186440/168864249-32435f00-2164-4d15-bf74-1e1914b27f17.png">
I'm also zoomed out on the page because the table I was working with had many columns. 

If I zoom in my new table looks more like yours:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/73186440/168864943-398d76be-87d1-4c76-8844-dd4b06e65f2c.png">
But even at that level of zoom I can fit 10 characters in a row when the column width is set to its minimum.

**Comment by trey-wallis** [comment]
Oh, you are zooming! I was wondering why the text was smaller but the buttons didn't resize. Do you think that all elements should resize when you zoom?

**Comment by trey-wallis** [comment]
Also, Notion has a limit on how far you can shrink a column. Do you have a recommendation of how much a user should be able to shrink a column? I could remove the restriction all together but then the header text wouldn't be visible. This might be good for types like a checkbox though. I could add a tooltip that would appear if you were to hover over the header or cells to show content.

**Comment by kerrywoolnough** [comment]
For users who zoom out for the purposes of fitting more content on the screen, I think it would be advantageous for all elements to resize when zooming so that columns aren't filled with additional whitespace.

I'd vote in favor of removing the restriction on column width (or make it very small, e.g. 2 digits), but I tend to prefer flexibility over dummy proofing. Revealing content when hovering sounds like a good idea.

**Comment by trey-wallis** [comment]
@kerrywoolnough I lowered the width to 20px. Could you test this in v3.5.0?

**Comment by kerrywoolnough** [comment]
Sure.

This is the narrowest width I can achieve for the first column (Default theme, turned off zoom). 

![image](https://user-images.githubusercontent.com/73186440/169297833-f2a99ab8-cb42-49e8-87b5-6ce914598c3c.png)

And zoomed all the way out (as I'd typically view my tables):

![image](https://user-images.githubusercontent.com/73186440/169298692-fcc03c75-a742-4c04-a67e-2422563dd78c.png)

It may also be worth noting that at size 13 font, after I've hit the minimum column width, trying to drag the column bound further results in the column title switching from 'No'. to 'N...' despite there being no (perceivable) change in width. I cannot reproduce this at or below size 12 font, but it it does occur at other font sizes >13.

![image](https://user-images.githubusercontent.com/73186440/169299745-8d107f04-d7a4-4894-b120-a85f763b5832.png)

![image](https://user-images.githubusercontent.com/73186440/169299785-60c0fa58-8a5c-4f11-835c-a85b287e7e4e.png)

**Comment by spiritualgeek** [comment]
Love the concept but the re-sizing seems too buggy and for some columns it just does not work (No handle top drag appears)

Text is also completely wonky and squashed up. See the image.
![2022-06-27_16-13-51](https://user-images.githubusercontent.com/53917562/175962771-4e8a5698-d678-4fbc-a451-3533cc1465c8.png)

It may become usable if this is solved

**Comment by trey-wallis** [comment]
Thank you @spiritualgeek for the feedback. This has been a tricky thing to implement. I have made a working prototype and I plan on adding it to the plugin today. The min-width will also be relative to the font-size of the theme which will solve the issue that the issue creator was experiencing. Cheers!

**Comment by trey-wallis** [comment]
@spiritualgeek Fixed in 4.1.0

**Comment by trey-wallis** [comment]
@kerrywoolnough Please check out the latest version in 4.1.0. I have completely reworked the column resizing system.
