### ISSUE TITLE
visual help when sorting

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#166]
**Is your feature request related to a problem? Please describe.**
you can't know visually by which column the table is sorted or if it's sorted at all

**Describe the solution you'd like**
add some kind of arrow to symbolize sorting asc, desc next to the header text

**Comment by trey-wallis** [comment]
I like this suggestion. Very good idea.

**Comment by trey-wallis** [comment]
@imeed166 Added in 4.2.0
