### ISSUE TITLE
[BUG]For a new table, Chinese cannot be entered when editing the header

### ISSUE THREAD

**Issue by MugenLee** [trey-wallis/obsidian-notion-like-tables#171]
Version Information
obsidian: v0.14.12
Theme: mini 5.1.7
notion-like-tables:v3.5.0

Specific issues:
For a new table, Chinese cannot be entered when editing the header

But when editing the table-body cell, you can enter Chinese

I am using the Windows 10 Microsoft Pinyin input method

**Comment by trey-wallis** [comment]
Hi @MugenLee. I will take a look at this.

**Comment by MugenLee** [comment]
> Hi @MugenLee. I will take a look at this.

OK 
Hope to fix it 
thanks

**Comment by MugenLee** [comment]
> 你好@MugenLee. 我会看看这个。
@trey-wallis 
I record a video：
You can see when input chinese in table-header, , it will not be able to input Chinese normally because it keeps flashing

https://user-images.githubusercontent.com/91043731/170640077-fbd58bfd-9820-4ab8-bd82-e530f908003b.mp4

**Comment by hqweay** [comment]
This also happens to the Japanese input method, it seems that the edit box has done some processing, so that the word selection box cannot be called normally here.

platform: Mac Monterey 12.3.1
plugin version: 3.5.3
obsidian version: v0..12.19

**Comment by MugenLee** [comment]
> Hi @MugenLee. I will take a look at this.

Will this issue be fixed?

I just upgraded to v4.2.0

This problem still exists, which prevents me from using this plugin
@trey-wallis

**Comment by trey-wallis** [comment]
@MugenLee Hi MugenLee. Yes, I will place this as my next bug fix. Cheers! :)

**Comment by MugenLee** [comment]
> @MugenLee Hi MugenLee. Yes, I will place this as my next bug fix. Cheers! :)

ok 
Hope to fix it :)

**Comment by trey-wallis** [comment]
@MugenLee I just installed the Pinyin simplified Chinese keyboard on my computer. Pretty cool!! Do you normally press numbers to select the Chinese word i.e. "1" or "2" or do you press "Enter" or do you click the word?

**Comment by trey-wallis** [comment]
Fixed in 4.2.4
