### ISSUE TITLE
[BUG]For newly created tables, part of the drop-down menu will be blocked

### ISSUE THREAD

**Issue by MugenLee** [trey-wallis/obsidian-notion-like-tables#172]
Version Information
obsidian: v0.14.12
Theme: mini 5.1.7
notion-like-tables:v3.5.0

Specific issues:
like this:

![image](https://user-images.githubusercontent.com/91043731/169649282-54f11c62-42b6-4547-8af9-1647a580e772.png)

**Comment by trey-wallis** [comment]
Fixed in 3.5.1. Check it out! :)
