### ISSUE TITLE
[BUG]for 'column' specifying date format, the table-cell cannot select date 

### ISSUE THREAD

**Issue by MugenLee** [trey-wallis/obsidian-notion-like-tables#173]
Version Information
obsidian: v0.14.12
Theme: mini 5.1.7
notion-like-tables:v3.5.0

Specific issues:
After specifying a "column" as the date format, click its cell, and the date selection control will appear

But it is only displayed, and cannot select a specific date

like this:
![image](https://user-images.githubusercontent.com/91043731/169649304-049b4a29-e156-49cf-8ed9-2fc3e35298d9.png)

**Comment by trey-wallis** [comment]
Fixed in 3.5.1. Thanks :)
