### ISSUE TITLE
Markdown table filter

### ISSUE THREAD

**Issue by lbgws2** [trey-wallis/obsidian-notion-like-tables#177]
i need filter in markdown table

By filtering column values, the table looks more concise .

and i like Links  rendered in cells ,i can put content below the table ,then click link to get there

**Comment by trey-wallis** [comment]
HI @lbgws2. That is a good suggestion. I will look into adding that. Is there a specific way you would like to filter values?

Also, is your comment about the links rendered in cells a suggestion or a comment? I didn't really understand.

**Comment by trey-wallis** [comment]
Added in 6.0.0
