### ISSUE TITLE
Way to adjust width

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-notion-like-tables#180]
Hello,

thanks for the amazing plugin! Is there a way to adjust the width of a table? I use pseudometa's Shimmering Focus theme and the table's width is quite narrow, which impacts readability.

<img width="2183" alt="CleanShot 2022-05-22 at 13 59 00@2x" src="https://user-images.githubusercontent.com/20352339/169694092-9d02c313-783c-46eb-827a-5fea775c647d.png">

_Originally posted by @cashew90 in https://github.com/trey-wallis/obsidian-notion-like-tables/discussions/175_

**Comment by trey-wallis** [comment]
@cashew90 I have moved your discussion item into the issues and have disabled discussions. I was be looking into this. Thanks! :)

**Comment by trey-wallis** [comment]
@cashew90 I have fixed this in version 4.1.0. It seems though like the theme is very laggy, at least for me on my machine. I was able to resize columns though. Let me know if you have any further issues :)

**Comment by cashew90** [comment]
Yes!! Amazing work, thank you! Interesting though that the theme is laggy on your machine... have never experienced performance issues with this theme in general.
