### ISSUE TITLE
Tag list disappears immediately after appearing

### ISSUE THREAD

**Issue by RomanPro100** [trey-wallis/obsidian-notion-like-tables#184]
Whenever I want to add a tag, the tag menu apeears for like 1 frame and then disappears, not allowing me to press any buttons or type anything. The only way to add tags is manually typing them in block edit.

https://user-images.githubusercontent.com/99795209/170103755-ead92899-4a18-4394-bc16-e80ecb9a12df.mp4

**Comment by trey-wallis** [comment]
@RomanPro100. Thank you for your bug report. Yes, I just realized that this is a consequence of a few changes I made to the menu system. I will be pushing out a fix in the next day or so. It will include a fix for the flashing and jumping on all the menu as well.

**Comment by trey-wallis** [comment]
Fixed in 3.5.3
