### ISSUE TITLE
Links to Subheadings Aren't Working in Preview or Reading Mode [BUG]

### ISSUE THREAD

**Issue by kerrywoolnough** [trey-wallis/obsidian-notion-like-tables#185]
**Describe the bug**
Within-page links to subheadings will open correctly when the page is shown in source mode, but in live preview or reading mode the link is not recognized (returns 'Click to create'). I am using version 3.5.2 of Notion-Like Tables. 

SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 20.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 6
	Safe mode: off
	Plugins installed: 9
	Plugins enabled: 7
		1: obsidian markmind
		2: Excel to Markdown Table
		3: Text Snippets
		4: Underline
		5: Hotkeys++
		6: Templater
		7: Notion-Like Tables

**Using Mobile App?**
No.

**Comment by trey-wallis** [comment]
@kerrywoolnough. Oh this is actually something I never tested. So I have no idea if it should be working

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
