### ISSUE TITLE
[BUG] Aliases break

### ISSUE THREAD

**Issue by MikeHawkesCapventis** [trey-wallis/obsidian-notion-like-tables#189]
**Describe the bug**
An aliased Obsidian link breaks the link, and creates a new column and breaks the table.

**To Reproduce**

1. Insert a new table
2. Add some text, for example: Link goes [[Internal Link|here]]

I would expect the link to appear in the table cell, with the word 'here' being a link: "Internal Link goes _here_"

**Screenshots**
![Screenshot 2022-06-01 at 10 59 13](https://user-images.githubusercontent.com/23031300/171379223-f6231f63-8b1a-496d-8f7c-01c3f045dc1f.png)

![Screenshot 2022-06-01 at 10 59 24](https://user-images.githubusercontent.com/23031300/171379286-c8b5007d-df3c-46e2-8afc-e2653dfb92d9.png)

**Debug Info**

SYSTEM INFO:
	Obsidian version: v0.14.15
	Installer version: v0.13.31
	Operating system: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 21.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 34
	Plugins enabled: 31
		1: Calendar
		2: Dataview
		3: Kanban
		4: Mind Map
		5: Note Refactor
		6: Checklist
		7: Editor Syntax Highlight
		8: Tag Wrangler
		9: Review
		10: Dictionary
		11: Juggl
		12: Natural Language Dates
		13: Pandoc Plugin
		14: Text expand
		15: Admonition
		16: Journey
		17: Longform
		18: React Components
		19: LanguageTool Integration
		20: Advanced Mobile Toolbar
		21: Recent Files
		22: Dangling links
		23: Minimal Theme Settings
		24: Outliner
		25: Graph Analysis
		26: Templater
		27: Obsidian Leaflet
		28: Hover Editor
		29: Paste URL into selection
		30: Excalidraw
		31: Notion-Like Tables

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Using Mobile App?**
No.

**Comment by brimwats** [comment]
confirmed, I use Aliases in my weekly note like [[2022-06-06\|Monday (06/06)]] but NLT makes them invalid link 
![Screenshot_20220613-193800_Obsidian](https://user-images.githubusercontent.com/73113656/173481881-052c4718-49df-4416-9049-2d968b231c7d.jpg)

**Comment by EhuddR** [comment]
Same here, I hope this will be fixed in the next major version.

**Comment by brimwats** [comment]
Aliases are continuing to break. 

here's an example table. 

![Screenshot_20220627-232132_Obsidian](https://user-images.githubusercontent.com/73113656/176107612-27cbbf7f-6614-4c6e-920d-4ffa200f2d8f.jpg)

it should look like this 

![Screenshot_20220627-232433_Obsidian](https://user-images.githubusercontent.com/73113656/176107911-c9268589-9a13-48d6-bcfd-78873b081b52.jpg)


but only unresolved links get turned into links, but they don't work

**Comment by trey-wallis** [comment]
@EhuddR @MikeHawkesCapventis @brimwats Fixed in 5.0.0. Please check it out! :)
