### ISSUE TITLE
[BUG] Need some way of exiting selection menu

### ISSUE THREAD

**Issue by brimwats** [trey-wallis/obsidian-notion-like-tables#190]
I'm disabled and often accidentally activate the selection menu (the menu with Edit...Sort...Type..etc. in it.) I cannot exit out of it without changing something when often I don't want to change anything. this is extremely annoying on mobile the menu is on the top left of this screenshot

![Screenshot_20220613-193800_Obsidian](https://user-images.githubusercontent.com/73113656/173482128-7b0e3a53-130a-45ad-8a5a-606987661249.jpg)

**Comment by trey-wallis** [comment]
@brimwats Hi brim. Thank you for your bug report. I have fixed this in 4.0.0. I am open to any further feedback.
