### ISSUE TITLE
Suggest links within a table

### ISSUE THREAD

**Issue by EhuddR** [trey-wallis/obsidian-notion-like-tables#192]
Hi! I think the title is self explanatory. 

**Is your feature request related to a problem? Please describe.**
I would like to say that your plugin is pretty useful but right now is not possible to obtain link sugestions inside a cell [[ ]]. This feature would be helpful if you link a lot of notes inside a table. 

**Describe the solution you'd like**
Get notes suggestion inside a table when you type [[ ]]. Just how obsidian works. 

Regards.

**Comment by trey-wallis** [comment]
@EhuddR Hi EhuddR. Thank you for your feature request. This would be pretty cool! I am not sure how to implement but I can see if the Obsidian API has any functionality that I can leverage. Do you know any other plugins which do something like this?
