### ISSUE TITLE
[FEATURE] All values disappear (text and tag change)

### ISSUE THREAD

**Issue by javiavid** [trey-wallis/obsidian-notion-like-tables#196]
**Describe the feature**
When changing column type between tag or text all values disappear

**To Reproduce**
1. Create table, with text column
2. Select column/type and change from text to Tag

**Expected behavior**
Values remain converted to tags or converted to text (from tags)

**Screenshots**

https://user-images.githubusercontent.com/7627504/175927194-3a1200bb-f359-4a23-9f5e-0d1ba2967a59.mp4

**Comment by brimwats** [comment]
this also happens to me. I've lost data because of it.

**Comment by trey-wallis** [comment]
@javiavid Hi Javiavid. Yes, this is currently a limitation in the table. If this happens to you, you can always go back to the source markdown and undo changes. However, I realize that this is something I should fix. I will add this to my higher priority log and push out a fix in the next week or two.

**Comment by trey-wallis** [comment]
@javiavid @brimwats @csss1234 Fixed in 4.3.1! :) Check it out

**Comment by javiavid** [comment]
I already tried it and it works!
Thank you
