### ISSUE TITLE
[Bug] The tags and checkboxes aren't persistently saved

### ISSUE THREAD

**Issue by RSant0s** [trey-wallis/obsidian-notion-like-tables#201]
**Version:** 4.0

**Obsidian Version:** v0.14.15

**Platform:** macOS Big Sur 11.6.7 

**To reproduce:**
1. Create a new table.
2. Change a column header to the tag or checkbox mode.
3.  In your table content insert some tags and tick some checkboxes.
4. Close the Obsidian and open it again.

**What happens:**

The table appears but without any tag and any checkbox selected. 😞

**Comment by NunoMMBarreto** [comment]
I am having the same problem. Actually, isn't persisted any kind of data

**Comment by ilkerduymaz** [comment]
I have the same problem but worse: the markdown file doesn't get updated with the data I input using the plugin interface, both with the new and legacy editor.

**Comment by maxchristman** [comment]
I am having the same problem. Any changes to tables in reading view do not appear in the markdown in editing view, leading them to not be saved. Unfortunately, this makes the tables unusable as is.

**Comment by csss1234** [comment]
Yes fully broken for me. Editing or Preview mode. Obsidian 0.15.9 on mac. I disabled some other plugins like Advanced Tables that I thought could be interfering. 


https://user-images.githubusercontent.com/45954264/187535022-dd190471-022b-47d9-a120-7e3bc68a8233.mov

**Comment by trey-wallis** [comment]
@csss1234 I will check this in the next few days.

**Comment by trey-wallis** [comment]
@ilkerduymaz I pushed out a fix in 4.2.6. Could you please try it?

**Comment by trey-wallis** [comment]
Checkboxes should be fixed in 4.3.0. Working on tags.

**Comment by trey-wallis** [comment]
@RSant0s @csss1234 @maxchristman Fixed in v5.0.0.
