### ISSUE TITLE
Adjusting the width of columns in multiple tables[BUG]

### ISSUE THREAD

**Issue by TheAussieTinker** [trey-wallis/obsidian-notion-like-tables#202]
**Describe the bug**

If a note has more than one table and you change the width of column 2  from table 1 for example the column 2 from table 2 would become the same width after you reopen the note. If I have multiple tables in the same note I would like to change the width of the columns manually for each table.

**To Reproduce**

1. change the width of a column
2. click on a different note
3. Reopen the original note
4. all other tables in the note have the same width as the one changed

**Expected behavior**

Each table has the ability to manually change the column width without adjusting to the width of a different table in the same note.

**Comment by trey-wallis** [comment]
@TheAussieTinker Hi TheAussieTinker. Yes, this is currently a limitation of the table. I plan on implementing a solution in the next week or two.

**Comment by trey-wallis** [comment]
@TheAussieTinker This is fixed in 4.3.1 :)
