### ISSUE TITLE
[BUG]Style report

### ISSUE THREAD

**Issue by YIRU69** [trey-wallis/obsidian-notion-like-tables#211]
**Describe the bug**
![image](https://user-images.githubusercontent.com/48148292/180009538-bc57d688-c234-4d9c-94bd-8647d0a9572e.png)
![image](https://user-images.githubusercontent.com/48148292/180010582-23b3f1ef-58ca-4ce9-bbc0-776d73f2338e.png)

**info**
ob-vision: 0.15.6
plugin-vision: Newest
theme: shimmering focus, dafault

**descirbe**
I want to achieve like table on obsidian. Could delect the "..." and display all the content?

**Using Mobile App?**
No

**Comment by YIRU69** [comment]
@trey-wallis 
It seem that some wrong when open auto-width. Could you find the error?
![image](https://user-images.githubusercontent.com/48148292/180646433-d5461506-c60b-4c3c-894d-e9c6078247a8.png)
![image](https://user-images.githubusercontent.com/48148292/180646448-4669faa6-27e5-44c0-b346-3f3638d1ef24.png)

**Comment by trey-wallis** [comment]
Hi @YIRU69. Would you mind sending me a screenshot of that markdown that you using for this table?

**Comment by YIRU69** [comment]
@trey-wallis hi, maybe you could try to zoom out with 'ctrl+=', then you could find the display problem. I thought it cause with font-size. I try to set 16px font size then the table look prefect. And set it 23px, the problem was appear above the picture. Could you fix it?

**Comment by trey-wallis** [comment]
@YIRU69 Sorry for getting back super late on this. I think I know what's happening. I will get to it this week. Cheers.

**Comment by trey-wallis** [comment]
@YIRU69 Fixed in v5.0.0.
