### ISSUE TITLE
Tags not readable in dark mode

### ISSUE THREAD

**Issue by icebruce** [trey-wallis/obsidian-notion-like-tables#212]
When creating tags using dark mode the colours are not well suited and its hard to read

**To Reproduce**
1. Switch to dark mode
2. Create a new table
3. Add a tag

**Expected behavior**
Would be nice if the tags use a different colour scheme to account for dark mode

**Screenshots**
![image](https://user-images.githubusercontent.com/66655064/180506734-b7706d96-bcaa-45a4-81f7-e30d4e15b705.png)

**Debug Info**
SYSTEM INFO:
	Obsidian version: v0.15.7
	Installer version: v0.14.6
	Operating system: Windows 10 Pro 10.0.19043
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 6

**Comment by trey-wallis** [comment]
@icebruce Hi ice. Thank you for your bug report. I will push out a fix for this this week. Thanks :)

**Comment by trey-wallis** [comment]
@icebruce Fixed in v5.0.0
