### ISSUE TITLE
Unexpected behavior when multiple tables appear in note

### ISSUE THREAD

**Issue by pm64** [trey-wallis/obsidian-notion-like-tables#232]
### Describe the bug

When multiple tables appear in a note, the position of the textbox of the cell being edited may be wrong.

### Steps to reproduce

1. Add a table to a note (Table A)
2. Add another table to the note (Table B)
3. Double-click a cell in Table A to begin editing cell. Observe that the position of the textbox is correct.
4. Double-click a cell in Table B. The position of the textbox incorrect; it is that of the cell with the corresponding coordinates in Table A.
5. Double-click another cell in Table B. The position of the textbox is incorrect; it is now positioned in the top-left corner of the viewport.

### Expected behavior

The textbox should appear in the same position as the cell prior to beginning cell editing.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 18
		1: Dataview v0.5.41
		2: Plaintext v0.1.0
		3: Reset Font Size v1.0.2
		4: Minimal Theme Settings v5.3.2
		5: Tasks v1.11.0
		6: Todoist Sync v0.0.1
		7: Collapse All v1.5.2
		8: Contextual Typography v2.2.4
		9: Readwise Official v2.0.1
		10: Annotator v0.2.4
		11: File Info Panel v1.2.5
		12: AidenLx's Folder Note v0.16.4
		13: Folder Note Core v1.3.5
		14: Paste URL into selection v1.7.0
		15: Excel to Markdown Table v0.4.0
		16: Advanced Tables v0.17.3
		17: Cycle through Panes v0.1.0
		18: AidenLx's Folder Note - folderv component v1.0.0

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@pm64 Fixed in 4.3.0. Focused tables has a bug that I will push out a fix for.
