### ISSUE TITLE
Chinese bug still not fixed

### ISSUE THREAD

**Issue by JiaanT** [trey-wallis/obsidian-notion-like-tables#233]
### Describe the bug

Chinese entered in source mode can be displayed in reading mode, but inserting a column with Chinese characters directly using obsidian-notion-like-tables does not work. After I inserted a column using obsidian-notion-like-tables ["shift+cmd+\"](url) and edited its title to Chinese words, it looks good, but if I switch to another note file and go back, all the changes disappeared.  

This bug is still existing in 4.2.5 ( #227 ) release.

### Steps to reproduce

- Create a table using `"shift + cmd + +"` or just type in source code
- Add a column using `"shift + cmd + \"` or click the `"New"` button
- Edit the inserted column by clicking the column name "New Column" - "Edit"
- Type in some Chinese characters in Header Name
- Click somewhere else, it displays correctly
- Switch to other note pages, or restart Obsidian, and switch back
- All the changes ( the new column and the Chinese characters) disappeared

### Expected behavior

Display and save Chinese correctly.

### Are you using the mobile app?

No

### Obsidian debug info

No result when searching "Show debug info"..

**Comment by trey-wallis** [comment]
Hi @JiaanT I will check this out. Sorry, I have been very busy recently.

**Comment by trey-wallis** [comment]
@JiaanT Should be fixed in v5.0.0. Please open a new issue if this continues to happen.

**Comment by JiaanT** [comment]
> @JiaanT Should be fixed in v5.0.0. Please open a new issue if this continues to happen.

Thank you so much!
