### ISSUE TITLE
[FR]Integration with Dataview

### ISSUE THREAD

**Issue by OmniNaut** [trey-wallis/obsidian-notion-like-tables#234]
### Problem

Coming from this plugin and this FR https://github.com/laozhou-in-germany/Chens_LMS_Public/issues/1

His plugin is based on the PPV LMS from August Bradley. August uses primarily Notion. Laozhu tried to port PPV (with his own enhancements) to Obsidian. He did a fine job. But the big problem is manipulation of dataview generated list is not user friendly. 
ONLT makes manipulation of lists really user friendly.
After talking with Laozhu he concluded that he could not integrate NLT in his port because there is no compatibility with Dataview.

### Solution

I reckon integration of compatibility with Dataview will besides the possibility to integrate with mentioned plugin also create new opportunities the way OLNT is used in Obsidian.

**Comment by trey-wallis** [comment]
@OmniNaut Currently text cells support dataview. You can empty codeblocks just like you normally would in a normal markdown page. I am going to close this. I may integrate dataview further in the future.
