### ISSUE TITLE
Editing table doesn't update markdown

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-notion-like-tables#239]
Yes fully broken for me. Editing or Preview mode. Obsidian 0.15.9 on mac. I disabled some other plugins like Advanced Tables that I thought could be interfering. 

https://user-images.githubusercontent.com/45954264/187535022-dd190471-022b-47d9-a120-7e3bc68a8233.mov

_Originally posted by @csss1234 in https://github.com/trey-wallis/obsidian-notion-like-tables/issues/201#issuecomment-1232125626_

**Comment by trey-wallis** [comment]
@csss1234 I just pushed out a fix in 4.2.6. Can you update and let me know if it works?

**Comment by csss1234** [comment]
Tested for just a minute or two, but looks good so far 👍
