### ISSUE TITLE
Didn't render normally

### ISSUE THREAD

**Issue by Quorafind** [trey-wallis/obsidian-notion-like-tables#24]
![image](https://user-images.githubusercontent.com/13215013/162598028-2a158359-3c19-41fa-a3ea-acd6cebec732.png)

Tested in default theme.

the original table code:

```table
| two | one |
| --- | --- |
| text | text |
| oooo | tttt |
```

**Comment by trey-wallis** [comment]
Hi @Quorafind. Thanks for leaving an issue. Could you give me explanation for what is happening?

#1 What is happening exactly
#2 What do you expect to happen
#3 Any other details

I will be adding a template to enforce this issue format.

Thanks,
Trey.

**Comment by Quorafind** [comment]
Sorry that I found I was wrong, it works well now.
