### ISSUE TITLE
Inserting new rows at any position

### ISSUE THREAD

**Issue by kkot** [trey-wallis/obsidian-notion-like-tables#249]
### Problem

Currently it is only possible to add new row at the bottom of table. It would be useful to be able to add it at any position.

### Solution

Add new option to the button at the right side of rows.

**Comment by trey-wallis** [comment]
@kkot Hi kkot. Thanks for the request. I actually had this implemented and just removed it. I will reconsider adding it to my new system for table management.

**Comment by trey-wallis** [comment]
Fixed in 6.3.0
