### ISSUE TITLE
Bold text does not render properly

### ISSUE THREAD

**Issue by zhl111** [trey-wallis/obsidian-notion-like-tables#250]
### Describe the bug

![image](https://user-images.githubusercontent.com/29135984/188898727-6b0880ea-9d02-4805-874e-e9e10972910e.png)

### Steps to reproduce

theme: minimal
1. Build forms
2. type `**xxxx**`

### Expected behavior

Render bold text normally

### Are you using the mobile app?

No

### Obsidian debug info

nothing
![image](https://user-images.githubusercontent.com/29135984/188899639-2a29f702-7e55-4ae7-8acc-c023c603b5d0.png)

### Relevant log output

```shell
Number Headings Plugin: Automatically numbered document
plugin:number-headings-obsidian:863 Number Headings Plugin: Automatically numbered document
plugin:number-headings-obsidian:863 Number Headings Plugin: Automatically numbered document
plugin:number-headings-obsidian:863 Number Headings Plugin: Automatically numbered document
```

**Comment by trey-wallis** [comment]
@zhl111 Fixed in v5.0.0.
