### ISSUE TITLE
Plugin doesn't respond since the new update

### ISSUE THREAD

**Issue by RichestHumanAlive** [trey-wallis/obsidian-notion-like-tables#251]
### Describe the bug

I was looking for a release for which the tags would be readable in dark mode  and so I decided to update the plugin (directly from obsidian) when I saw that this [issue]( https://github.com/trey-wallis/obsidian-notion-like-tables/issues/212) had already been opened.

![image](https://user-images.githubusercontent.com/47452191/189031989-cf89b67e-e761-4ade-85af-43c8084bbb24.png)

After updating the plugins and followed instructions about blocs, nothing was working as before.

Same issue with a newly created Vault.

I tested many realises and I found that from the [4.2.6](https://github.com/trey-wallis/obsidian-notion-like-tables/releases/tag/4.2.6) release, the plugin seems not working.
I have restarted obsidian several times but no change.

![image](https://user-images.githubusercontent.com/47452191/189030662-8e5719db-2c16-44d3-8334-0caebdd0f9de.png)

Cannot edit headers or add new column or new row, cannot format table etc.

Switching back to [4.2.5](https://github.com/trey-wallis/obsidian-notion-like-tables/releases/tag/4.2.5) makes everything working fine again.

### Steps to reproduce

1. update the plugin
2. restart obsidian

### Expected behavior

Readable tags in dark mode

### Are you using the mobile app?

No

### Obsidian debug info

Dataview: version 0.5.41 (requires obsidian 0.13.11)
app.js:1 Total plugin setup: 807ms
dataview: 444ms
notion-like-tables: 304ms
periodic-notes: 31ms
heatmap-calendar: 22ms
hot-reload: 5ms
index.ts:151 Dataview: all 109 files have been indexed in 0.281s (109 cached, 0 skipped).

**Comment by crabbuilder** [comment]
the dark mode tags don't render for me either but the plugin does still work just only in reader mode
![image](https://user-images.githubusercontent.com/20156531/189264886-14e0942c-2987-410f-bddc-68218456c108.png)

**Comment by trey-wallis** [comment]
@RichestHumanAlive @crabbuilder Tags have been fixed in v5.0.0. Table should be working properly. You will need to do a migration for your tables though. Please see: "Migration tool" in the documentation

**Comment by RichestHumanAlive** [comment]
@trey-wallis Huge thanks for the update.  We don't say it enough but it takes a lot of time and work to maintain an open source tool/project that can help many people around the world.  Thanks legend.
