### ISSUE TITLE
Number columns don't support floating point numbers

### ISSUE THREAD

**Issue by desk7** [trey-wallis/obsidian-notion-like-tables#252]
### Describe the bug

If you write a floating point number (eg. 2.5) in a text-type column, and then convert the column into a Number-Type column, the dot disappears and you see 25.
In the editing view, the number is still 2.5

### Steps to reproduce

1. add a Notion-like table to a note
2. write a floating point number into a cell (eg 2.5).
3. Set the type of the column to "Number"
4. The number shown in the preview mode is 25 (ie the number without the dot)

### Expected behavior

Number-type column should recognize floating point numbers and render them properly.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.19043
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Notion-Like Tables v4.3.1

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
