### ISSUE TITLE
Feature Request: More opt-in or opt-out options

### ISSUE THREAD

**Issue by Pachtjuilaard** [trey-wallis/obsidian-notion-like-tables#255]
### Problem

I would like more fine-grained control over which table becomes a Notion-Like Table. Most of my tables have block-ids, but they contain code, and that code doesn't get rendered. 

### Solution

Would it be possible to only turn some tables into NLTs, for example only those whose block-ids contain "^nlt-", or opt-in/out using a frontmatter key?

**Comment by trey-wallis** [comment]
Hi @Pachtjuilaard. This will be part of version 5.0.0. Stay tuned :)

**Comment by trey-wallis** [comment]
@Pachtjuilaard Just released v5.0.0. Please check it out!
