### ISSUE TITLE
Checkbox UI is not in center

### ISSUE THREAD

**Issue by jumpingfrog0** [trey-wallis/obsidian-notion-like-tables#264]
### Describe the bug

<img width="679" alt="image" src="https://user-images.githubusercontent.com/7556575/192537159-96c7ea6f-701d-48fd-bcc5-67cf974bfc83.png">

Checkbox UI is not in center
my theme is Things.

### Steps to reproduce

| New Column | New Column | title |
| ---------- | ---------- | ----- |
| aaaaaaa    | [ ]        | aaa   |
| adfa       | [x]        |       |
| bbb        |            |       |
^Iz97ZI

### Expected behavior

Checkbox UI in  the center

### Are you using the mobile app?

No

### Obsidian debug info

Obsidian version : 0.15.9

### Relevant log output

```shell
no
```

**Comment by trey-wallis** [comment]
Hi @jumpingfrog0. Thank you for your issue. I will try to reproduce this with that theme.

**Comment by nihitkhandelwal-eng** [comment]
+1
You can use this CSS to correct it for now

.NLT__checkbox-cell {
    width: 10%;
    padding-right: 10%;
    padding-left: 60%;
}

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
