### ISSUE TITLE
Bug: Cursor moves to end of line after typing anywhere in cell

### ISSUE THREAD

**Issue by Pachtjuilaard** [trey-wallis/obsidian-notion-like-tables#281]
### Describe the bug

The cursor always moves to the end of the line after typing anything. So if I want to turn text inside a cell into a link, I can't properly put the [[ at the start of the line as the cursor is constantly moving back.

### Steps to reproduce

1. Click on a cell.
2. Move cursor to start of text in the cell.
3. Type anything.
4. Watch the cursor move to the back. 

### Expected behavior

The cursor should stay in place.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 17.7.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: ITS Theme
	Snippets enabled: 18
	Restricted mode: off
	Plugins installed: 61
	Plugins enabled: 56
		1: Advanced URI v1.28.0
		2: Advanced Tables v0.17.3
		3: Banners v1.3.3
		4: Breadcrumbs v3.6.3
		5: Commander v0.1.0
		6: Contextual Typography v2.2.4
		7: Dice Roller v8.6.9
		8: Dynamic Table of Contents v0.0.27
		9: Excel to Markdown Table v0.4.0
		10: Hotkeys++ v0.2.7
		11: Icon Folder v1.3.31
		12: Initiative Tracker v8.0.11
		13: Link Headers Directly v1.0.2
		14: macOS Keyboard Navigation v1.1.2
		15: Markdown Attributes v1.2.0
		16: Natural Language Dates v0.6.1
		17: Note Refactor v1.7.1
		18: Obsidian Leaflet v5.0.4
		19: Obsidian42 - BRAT v0.6.35
		20: Paste image rename v1.5.0
		21: Plugin Changelogs v1.3.0
		22: Quick Explorer v0.2.1
		23: QuickAdd v0.5.5
		24: Second Window v1.0.5
		25: Tabout v1.0.0
		26: Tag Wrangler v0.5.3
		27: Templater v1.14.3
		28: TTRPG Statblocks v2.21.8
		29: Various Complements v7.1.1
		30: Customizable Menu v2.2.0
		31: Waypoint v1.3.0
		32: Folder Note Core v1.3.5
		33: AidenLx's Folder Note v0.16.4
		34: Workbench v1.6.1
		35: MetaEdit v1.7.2
		36: Hotkey Helper v0.3.15
		37: Admonition v9.0.5
		38: Wikilinks to MDLinks v0.0.12
		39: Quick Switcher++ v2.0.7
		40: Pane Relief v0.4.0
		41: Supercharged Links v0.8.0
		42: Style Settings v0.4.12
		43: RPG Manager v2.0.3
		44: Buttons v0.4.17
		45: Excalidraw v1.7.22
		46: Settings Search v1.2.0
		47: Custom Frames v2.4.4
		48: Obsidian Better Internal Link Inserter v1.0.0
		49: DB Folder v2.7.0
		50: Dataview v0.5.46
		51: Fantasy Calendar v2.3.10
		52: Inline Scripts v0.23.2
		53: Meta Bind Plugin v0.2.0
		54: Find orphaned files and broken links v1.8.0
		55: Metadata Menu v0.2.6
		56: Notion-Like Tables v5.0.2

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@Pachtjuilaard Will fix this today.

**Comment by trey-wallis** [comment]
@Pachtjuilaard Fixed in 5.0.3
