### ISSUE TITLE
Bug: Cell editor immediately closes on mobile, unable to edit anything

### ISSUE THREAD

**Issue by Pachtjuilaard** [trey-wallis/obsidian-notion-like-tables#282]
### Describe the bug

Clicking on a cell immediately closes it on mobile.

### Steps to reproduce

1. Open any NLT table
2. Edit any cell
3. See the text box open, then close immediately after.

### Expected behavior

The textbox should stay open, until I press enter or click anywhere outside the text box. 

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Operating system: ios 15.7 (Apple iPad)
	Obsidian version: 1.3.2 (69)
	API version: v0.15.9
	Login status: logged in
	Catalyst license: none
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: ITS Theme
	Snippets enabled: 18
	Restricted mode: off
	Plugins installed: 61
	Plugins enabled: 27
		1: Dataview v0.5.46
		2: Force note view mode v1.1.1
		3: Icon Folder v1.3.31
		4: Link Headers Directly v1.0.2
		5: Templater v1.14.3
		6: MetaEdit v1.7.2
		7: TTRPG Statblocks v2.21.8
		8: Hotkey Helper v0.3.15
		9: Breadcrumbs v3.6.3
		10: Contextual Typography v2.2.4
		11: Hotkeys++ v0.2.7
		12: Paste image rename v1.5.0
		13: Style Settings v0.4.12
		14: Meta Bind Plugin v0.2.0
		15: Commander v0.1.0
		16: Various Complements v7.1.1
		17: Dynamic Table of Contents v0.0.27
		18: Plugin Changelogs v1.3.0
		19: Quick Switcher++ v2.0.7
		20: Note Refactor v1.7.1
		21: Hover Editor v0.11.4
		22: Settings Search v1.2.0
		23: Supercharged Links v0.8.0
		24: Advanced Mobile Toolbar v1.7.7
		25: RPG Manager v2.0.3
		26: Notion-Like Tables v5.0.2
		27: Custom Frames v2.4.4

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@Pachtjuilaard Hi Pachtjuliaard. Thank you for your bug report. I saw this problem yesterday on my phone, it's an easy fix. I just need to remove the code that closes menus on scroll. However, I'm not quite sure how to handle scrolling on desktop. On desktop, if you scroll, would you expect a menu to close or for it just to stay open?

**Comment by Pachtjuilaard** [comment]
Hi! I would expect a menu to stay open on scrolling, and would expect it to only close on pressing esc, clicking outside the menu, or pressing the Return key or Tab key.

**Comment by trey-wallis** [comment]
@Pachtjuilaard Fixed in 5.0.4. I haven't been developing much for mobile, so there are still a few issues. I will gradually work on them though. The actual table logic is sound, it's just weird UI stuff for mobile.
