### ISSUE TITLE
Tab key to navigate between cells

### ISSUE THREAD

**Issue by luckman212** [trey-wallis/obsidian-notion-like-tables#283]
### Problem

I noticed an old issue #35 but it's closed. Now that 5.x is out, I think maybe this either regressed or might need to be updated. I never used 4.x so I can't be sure.

Either way, the FR is to be able to navigate and do data entry within an NLT without touching the mouse. It's OK if the during the initial setup of the table you need to click "New" to add columns etc but after that, it would be ideal to be able to just tab through.

### Solution

Example, If you are on cell **B2** below, and hit <kbd>TAB</kbd>:

(❙ = _cursor_)

| |A|B|
|:---|---|---|
|1|Foo|Bar|
|2|Baz|Quux ❙|

NLT should generate a new row **3** and place the cursor in column **A3**.

| |A|B|
|:---|---|---|
|1|Foo|Bar|
|2|Baz|Quux|
|3|❙| |

Similarly, if you're in cell **A2** and press <kbd>SHIFT</kbd>+<kbd>TAB</kbd>

| |A|B|
|:---|---|---|
|1|Foo|Bar|
|2|Baz ❙|Quux|
|3| | |

the cursor should move back up to **B1**

| |A|B|
|:---|---|---|
|1|Foo|Bar ❙|
|2|Baz|Quux|
|3| | |

**Comment by trey-wallis** [comment]
@luckman212 Hi Luckman. Yes, this is the plan for 5.1.0.

**Comment by RayBB** [comment]
This is also the main feature I'd need to start using this plugin more often!

**Comment by meeebee** [comment]
I second this request, as it greatly  makes data entry faster.

**Comment by trey-wallis** [comment]
@luckman212 @RayBB @meeebee Implemented in 6.6.0 :)

**Comment by RayBB** [comment]
@trey-wallis this new feature is pretty solid thanks for the hard work :)

Do you plan to make it so that you can tab while you're typing?  Right now you always have to press enter to leave typing mode to tab.
