### ISSUE TITLE
HTML tag <br> is not working

### ISSUE THREAD

**Issue by fightyz** [trey-wallis/obsidian-notion-like-tables#284]
### Describe the bug

`<br>` tag is not rendering correctly whether in Live Preview mode or Reading mode.
![image](https://user-images.githubusercontent.com/1697504/193796504-58a82785-6992-4ee4-a8e1-dfc2d994c064.png)

### Steps to reproduce

1. <kbd>cmd</kbd>+<kbd>p</kbd> to create a NLT table.
2. Input some text with `<br>` in a cell.

### Expected behavior

Rendering line break.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 16
		1: Vimrc Support v0.7.2
		2: Custom Attachment Location v0.0.9
		3: Style Settings v0.4.11
		4: Number Headings v1.10.0
		5: Admonition v9.0.5
		6: Obsidian Git v2.1.1
		7: Kanban v1.3.20
		8: Recent Files v1.3.3
		9: Calendar v1.5.10
		10: Periodic Notes v0.0.17
		11: Vim Input Method Switch v1.0.8
		12: Excalidraw v1.7.20
		13: obsidian markmind v1.5.7
		14: Notion-Like Tables v5.0.2
		15: Templater v1.14.2
		16: Minimal Theme Settings v5.3.2

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
