### ISSUE TITLE
Nested folder for "NLT table definition files"

### ISSUE THREAD

**Issue by nihitkhandelwal-eng** [trey-wallis/obsidian-notion-like-tables#285]
### Problem

As of 04-Oct-22, we are asked not to include any slashes for the folder for that folder.
So the folder has to be in the root directory.

### Solution

It would be helpful if the folder can be nested under folders.

### Additional details

If this is already implemented then please can you assist me in achieving the nested folder thing.
Many thanks

**Comment by trey-wallis** [comment]
Not relevant for 6.0.0
