### ISSUE TITLE
Allow multiple lines text

### ISSUE THREAD

**Issue by ShravanSunder** [trey-wallis/obsidian-notion-like-tables#287]
### Problem

The current text implementation doesn't allow multiple lines.  For example if you hit shift+enter in notion tables you can enter multiple lines.

### Solution

Allow multiple lines with interaction similiar notion such as (SHIFT+ENTER) or (ALT+ENTER)

**Comment by trey-wallis** [comment]
@ShravanSunder Added in 6.2.0
