### ISSUE TITLE
Bug: Plugin prevents Rendering of all *normal* tables

### ISSUE THREAD

**Issue by chrisgrieser** [trey-wallis/obsidian-notion-like-tables#29]
First of all thank you for this plugin. This will make work with tables so much better.
Also has a good README.

---

**Describe the bug**
When the plugin is enabled, normal tables (without the type definition at in the first row, but with normal content in them) do not render anymore.

This means we have set types in *all* our existing tables (for some users hundreds), if we want to use this plugin. Also, it seems there is no way of using normal tables while this plugin is active.

**To Reproduce**
1. Enable Plugin.
2. Go to note which already has a normal table
3. Enter Reading Mode

**Expected behavior**
Normal Markdown tables one already has should render normally.

**Possible Solution**
Some way of indicating that a table should be a notion-like table. The plugin would then only render those tables, and leave normal tables alone?

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by trey-wallis** [comment]
Hi Chris,

Thanks for leaving this issue. This is not so much a bug, as it is a feature request. I had designed the plugin to turn all tables into Notion-Like tables in reading mode. Although, considering that I am possibly not the typical Obsidian user, I agree that there should be a way of choosing if you want to render a table as a Notion-Like table.

Possible solutions that I am considering:
1. If a table has a type definition row (1st row after the hyphen row) with the words - "text", "tag", "number" that we can assume that the table is a Notion-Like table
- This would be an easy solution with no extra work
2. Add frontmatter to convert all tables on a note to Notion-Like tables

Any thoughts?

**Comment by chrisgrieser** [comment]
I think 1) would be totally fine, at least for me, since I think it would be highly unlikely to have solely those values by chance on the first row

**Comment by trey-wallis** [comment]
@chrisgrieser I just added this feature. Give it a try!
