### ISSUE TITLE
Insert row above another one - Tables in Templates - Links to note in Tables

### ISSUE THREAD

**Issue by arale33** [trey-wallis/obsidian-notion-like-tables#291]
### Problem

I started using Notion Like Table and it works great after the recent update. 

Still I face 3 issues. 

1) how do I insert a row above another? 

2) when I set up a table in a template, how do I prevent the table in the template note to get filled when I filled the table in the note based on that template? 

3) Also it doesn't seem that I can insert a link to another note within a table. Is that right?

Thank you

### Solution

As said above.

**Comment by trey-wallis** [comment]
1. Fixed in 6.3.0
2. No longer relevant
3. Fixed in 6.2.0
