### ISSUE TITLE
filter is needed so much

### ISSUE THREAD

**Issue by a1576799** [trey-wallis/obsidian-notion-like-tables#297]
### Problem

I would like to suggest that the notion-like-table has a feature of filter.

### Solution

Thank you for this great plugin.

I would like to suggest that the notion-like-table has a filter feature, as we know that notion database table is famous for its filters. Looking forward to this feature!

Also, by any chance, could we have more kinds of views like calendar or list? 

Many thanks.

**Comment by trey-wallis** [comment]
@a1576799 As of right now, I don't plan on adding any other views. Maybe check out: https://github.com/marcusolsson/obsidian-projects. They have tables, boards, calendar and gallery.

**Comment by trey-wallis** [comment]
@a1576799 Basic filtering added in 6.8.0 :)

**Comment by SafwanSa** [comment]
One more missing feature in filters is "OR" & "AND" conditions as I want to filter by multiple columns at the same time.
