### ISSUE TITLE
Ability to storage tables folder within a folder

### ISSUE THREAD

**Issue by chrisweis** [trey-wallis/obsidian-notion-like-tables#298]
### Problem

Expectation: "I can move the `_notion-like-tables` folder to be a subfolder of my Assets folder"
Reality: The plugin hung with "Loading table..." when I modified the folder location to be "Assets/_notion-like-tables"

### Solution

Would be great if full paths could be supported for the `_notion-like-tables` folder

### Additional details

Why?  Because I like to keep my root folder as clean and simple as possible.

Thanks for the plugin.  It really improves Obsidian's lack of robust table support!

**Comment by mustafaalbazy** [comment]
I just experienced the same exact issue. Would be much better if we can specify the path such as `/folder/_notion-like-tables`. 

Thanks.

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
