### ISSUE TITLE
Number columns sorting by text

### ISSUE THREAD

**Issue by chrisweis** [trey-wallis/obsidian-notion-like-tables#299]
### Describe the bug

When I add a column and set it to "Number" format, then sort by that column, it doesn't sort numerically.  Example:

⬇️Number
Number
6990
699
674
1064 <--- should be row 2 in the list

### Steps to reproduce

1. Add a column
2. Change type to number
3. Enter the values of random numeric values
4. Sort by the number column
5. Note the order

### Expected behavior

Should sort the same as Excel or Google Sheets.  Larger number values ordered versus smaller number values.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.14.15
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 46
	Plugins enabled: 37
		1: Advanced Tables v0.17.3
		2: Paste URL into selection v1.7.0
		3: Dataview v0.5.46
		4: Obsidian TODO | Text-based GTD v0.2.7
		5: Footnote Shortcut v0.0.9
		6: Recent Files v1.3.3
		7: Shortcuts extender v2.2.0
		8: Tag Wrangler v0.5.3
		9: Quick Explorer v0.2.1
		10: Macros v0.1.0
		11: Day Planner v0.5.8
		12: Hotkeys++ v0.2.7
		13: Diagrams v1.5.0
		14: Omnisearch v1.6.4
		15: Templater v1.14.3
		16: Copy as HTML v1.0.5
		17: Workspaces Plus v0.3.2
		18: Maximise Active Pane v0.0.3
		19: Quick Switcher++ v2.0.7
		20: Auto Link Title v1.2.5
		21: Style Settings v0.4.12
		22: Collapse All v1.5.3
		23: Calendar v1.5.10
		24: Commander v0.1.0
		25: Tasks v1.15.0
		26: Obsidian Raindrop v1.0.3
		27: Folder Note v0.7.3
		28: Periodic Notes v0.0.17
		29: Itinerary v1.3.0
		30: Todoist Plugin v1.9.0
		31: CardBoard v0.3.3
		32: Drag-n-Drop for blocks v1.1.0
		33: Copy Block Link v1.0.4
		34: Excalidraw v1.7.22
		35: Kanban v1.4.5
		36: Pandoc Plugin v0.4.1
		37: Notion-Like Tables v5.0.5

**Comment by trey-wallis** [comment]
Thanks for finding this :)

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
