### ISSUE TITLE
Checkbox and date cell types

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#30]
Thank you for the plugin. 
A good addition imo would be a checkbox cell type that automatically create a checkbox in every row.
And a date cell type with a date picker that appears when focusing on the cell.

**Comment by trey-wallis** [comment]
Hi Immed,

Thanks! I have had a good time working on it so far.

Thank you for all of your suggestions. I think all of them are doable. I will add them to my roadmap.

**Comment by trey-wallis** [comment]
@imeed166 I have been pretty busy recently but I just got done publishing a very heavy update. I will implement these two types tomorrow :) Stay tuned

**Comment by trey-wallis** [comment]
@imeed166 Added in 3.1.0. Check it out! :)

**Comment by imeed166** [comment]
Thank you, it works nicely.
