### ISSUE TITLE
Date type not working

### ISSUE THREAD

**Issue by DiGregorioC** [trey-wallis/obsidian-notion-like-tables#304]
### Describe the bug

When I select a column as date, it removes anything I already have in it, even dates formatted as YYYY-MM-DD, but then I can not do anything with the columns. I click in each cell and nothing happens, and I can not type or do anything in the cell

### Steps to reproduce

When I select a column as date, it removes anything I already have in it, even dates formatted as YYYY-MM-DD, but then I can not do anything with the columns. I click in each cell and nothing happens, and I can not type or do anything in the cell

### Expected behavior

I should be able to select or enter a date

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 1
		1: Notion-Like Tables v5.0.5

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Fixed in 6.0.0
