### ISSUE TITLE
Buttons to add row under or above current one

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#32]
**Is your feature request related to a problem? Please describe.**
I can't make a row under or above the current one in preview mode.

**Describe the solution you'd like**
Make 2 additional buttons in the 3 dots menu to the right :
1. Button to add a row under the current one
2. Button to add a row above the current one

**Describe alternatives you've considered**
Add the row in edit source mode.

**Comment by trey-wallis** [comment]
@imeed166 Thank you for this suggestion. I am thinking about making both the columns and rows draggable, so you can reorder them. Would that cover the functionality that you're describing here?

**Comment by imeed166** [comment]
That would be a workaround to what I'm describing, yes, but with more steps.
For example, in a table with 3 rows. If I want to create a row under the second row, I would have to create a 4th row then drag it under the second row.

**Comment by trey-wallis** [comment]
@imeed166 Implemented in 1.2.0. Check it out!
