### ISSUE TITLE
Ability to show up a list of linking suggestions

### ISSUE THREAD

**Issue by SaifEl-Deen** [trey-wallis/obsidian-notion-like-tables#321]
### Problem

If I type [ it doesn't auto complete to [[]] like it normally does in the editor
Also if I manually type [[]] and then try to type the first letter of the note I want to link for example [[f]], it doesn't show up a list of possible notes with the letter typed just as what happens in the editor

Update: This problem affects teh graph view as well, if I mention a certain note in a notion-table note, the linking doesn't appear on the graph view.

### Solution

Idk how this gets implemented but I guess it is done through embedding this function from the original app code/libraries

**Comment by trey-wallis** [comment]
@SaifEl-Deen I will be adding that this week :)

**Comment by MSBack** [comment]
> @SaifEl-Deen I will be adding that this week :)

Really looking forward to it! This plugin is immensely helpful, and this will make it even more so 👍

**Comment by trey-wallis** [comment]
@azyrust @MSBack @SaifEl-Deen @dex0501 Added in 6.11.0 :)

**Comment by MSBack** [comment]
> @azyrust @MSBack @SaifEl-Deen @dex0501 Added in 6.11.0 :)

Thanks a lot for the rapid development. This feature takes Notion-like tables to the next level!
