### ISSUE TITLE
Is it possible to embed the Table directly on the markdown file?

### ISSUE THREAD

**Issue by KoichaDev** [trey-wallis/obsidian-notion-like-tables#322]
### Problem

Sometimes there are situation I don't want the table to create a new markdown. I want the table to be written directly on the current file I am editing. situations

### Solution

Using Notion table you created, but directly adding on the current markdown file we are editing.

**Comment by ramonskovitch** [comment]
I too would like to do this in a code block:  ```notion-like-tables I am finding that ita more intuitive and efficient to create on the run.

**Comment by DutchPete** [comment]
I agree.

**Comment by trey-wallis** [comment]
@jem2go @ramonskovitch @dutchpete @koichadev @raybb @mahmoudmagby-7 @icebruce @senseofeternity @asabi @roseviet @seddanielsson @sjmgarnier Added in 6.14.0.

**Comment by Lmasey** [comment]
I would like to do this too, I attempted to open the files above, but I'm getting a 404 error.

**Comment by trey-wallis** [comment]
@Lmasey Sorry, I am in the process of updating documentation. Should be sorted out in the next hour :)

**Comment by trey-wallis** [comment]
@Lmasey Please see: https://trey-wallis.github.io/obsidian-dashboards/other/embedding-dashboards

**Comment by Lmasey** [comment]
Thank you!! I'm so excited to use this plug-in!You can help me support my 6th grade math classroom!Donors Choose: https://www.donorschoose.org/ms-maseyAmazon:https://www.amazon.com/hz/wishlist/ls/1YW3SZETZMC1R?ref_=wl_shareInterested in AVON https://www.avon.com/repstore/noturmomsavon?rep=noturmomsavonOn Jul 3, 2023, at 10:27 PM, Trey Wallis ***@***.***> wrote:﻿
@Lmasey Sorry, I am in the process of updating documentation. Should be sorted out in the next hour :)

**Comment by Lmasey** [comment]
Thank you! I will try it tonight when I'm on my computer:)You can help me support my 6th grade math classroom!Donors Choose: https://www.donorschoose.org/ms-maseyAmazon:https://www.amazon.com/hz/wishlist/ls/1YW3SZETZMC1R?ref_=wl_shareInterested in AVON https://www.avon.com/repstore/noturmomsavon?rep=noturmomsavonOn Jul 4, 2023, at 2:36 PM, Trey Wallis ***@***.***> wrote:﻿
@Lmasey Please see: https://trey-wallis.github.io/obsidian-dashboards/other/embedding-dashboards
