### ISSUE TITLE
Undo system

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-notion-like-tables#324]
### Problem

Currently if you make a change, such as deleting a column, there is no way to get it back.

### Solution

Undo system that caches the `tableState` operations preformed. Uses the same hotkeys as Obsidian ctrl + z, ctrl + shift + z

**Comment by trey-wallis** [comment]
@raybb @icebruce added in 6.9.0

**Comment by trey-wallis** [comment]
TODO
- add undo for filter rules
- add redo implementation for tag-cell-add-command

**Comment by RayBB** [comment]
Fantastic!! Thank you :)
