### ISSUE TITLE
Keep header visible when scrolling

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#33]
**Is your feature request related to a problem? Please describe.**
When scrolling a long table, I can't see the header (unlike notion tables)

**Describe the solution you'd like**
Make the header of the table appear at the top when scrolling a long table.

**Describe alternatives you've considered**
Scroll to the top of the table to see the header again.

**Comment by trey-wallis** [comment]
@imeed166 This is something that I will have to look into. It's going to take a little bit of ingenuity :)  I am going to place a few other features as higher priority first if that's okay.

**Comment by imeed166** [comment]
Of course, take your time.

**Comment by trey-wallis** [comment]
@imeed166 I plan on adding this + virtualized table rows this week. :)

**Comment by trey-wallis** [comment]
@imeed166 Added in 6.3.0
