### ISSUE TITLE
Files go into specific folder??

### ISSUE THREAD

**Issue by Viyyi** [trey-wallis/obsidian-notion-like-tables#339]
### Problem

idk if its possible but for example I want to create a books table and I make the books links [[book name]] is it possible that I can make all the files in the books table be sent/saved to a particular folder? 
Not sure if it is possible as I am totally new to obsidian

### Solution

Something that would it easy to organize my links? outside of the table in specific folders

**Comment by trey-wallis** [comment]
@Viyyi Hi Viyya. Good question. I will be adding the suggestion so in the future, you won't have to do this manually, but for right now, here is process.

Include the folder that you want to reference or create in your link
[[myFolder/myNote]]

If you want to display just the link name then make an alias using the pipe symbol `|`

[[myFolder/myNote|myNote]]
