### ISSUE TITLE
Create new row with keyboard

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#34]
**Is your feature request related to a problem? Please describe.**
Whenever I want to add a row in preview mode, I have to use the mouse.

**Describe the solution you'd like**
Create a keyboard shortcut to add a row (under/above) the current one (for example : `cmd+enter` for mac).

**Comment by trey-wallis** [comment]
I plan on releasing this later this week with an accessibility. Thanks for the suggestion.

**Comment by trey-wallis** [comment]
@imeed166 Added in 2.2.0. Check it out! :)

**Comment by imeed166** [comment]
Thank you, just one thing, If you could put the cursor on the first cell (first column) of the new row when pressing the keyboard shortcut, Instead of selecting it manually, that'd be better imo.

https://user-images.githubusercontent.com/38974541/166088188-8b7b34e5-8d4d-408e-85a3-8b3213c1457c.mov

**Comment by trey-wallis** [comment]
@imeed166 Fixed in 2.3.5.

**Comment by trey-wallis** [comment]
@imeed166 For any further discussion on these items. Please open a new issue. Thanks.
