### ISSUE TITLE
[FR] Embedded display of NLT tables

### ISSUE THREAD

**Issue by SPiCaRiA** [trey-wallis/obsidian-notion-like-tables#345]
### Problem

What I love about NLT (and what I believe that essentially differentiates NLT from other notion-like database plug-ins):
NLT is a **table** extension, not (a shell of) the dataview-ish file query engine. Which gives a lot more flexibility on what you put in the table cells (of course they can be links to your notes), with the rich feature of the notion database.

Therefore, I think it is a game-chaning thing to allow people embed NLT tables in their notes, as an "advanced table" that fits some complex scenarios. Currently, NLT relies on an individual view to display and interact with the tables, which cannot be applied on Markdown notes directly. We might need a thorough plan on the implementation of this.

### Solution

I know this plug-in started as an embedded table extension, and switched to current solution after realizing some constraints of the embedded editor. At this point, I'm thinking of the trade-offs in this way:

- **The current table view**
  - Pros: flexible, easier support on various features
  - Cons: separated from the notes; if the table is not used/displayed in any note, we lose the context of the data in the table and connections between our knowledge concepts and the great supporting tables
- **The embedded table**
  - Pros: embedded in note, surround with context
  - Cons: not flexible enough to support advanced features

Therefore, my proposed solution here focus on rendering an **immutable** view of the underlying table file. By saying **immutable**, I'm talking about the editing features of the table files. Which is to say, we only display the table in notes, without allowing users to edit it unless they open the table view.

From the Obsidian plug-ins I've seen, the **immutable** rendering has two popular ways of implementation:
1. Dataview-ish: put some metadata in a code block, and automatically render it in view mode
  - Pros: clean, real-time rendering, more/easier control on how the table will be rendered
  - Cons: not part of the native note, not portable
2. Text-expand-ish: put some metadata in a code block, and generate the equivalent native Markdown syntax after an explicit command execution
  - Pros: use native Markdown table, portable
  - Cons: less control and flexibility

It seems that the Dataview-ish approach is now the main stream among the Obsidian plug-ins, and I'm behind on this approach as well, given the rich functionalities of this plug-in and possible future features. Please let me know what you think!

**Comment by DutchPete** [comment]
I discovered this plug-in just today and was so impressed, I loved it immediately.
The 1<sup>st</sup> thing that came to my mind was “I want to be able to have this in my notes”.

So, I fully support @SPiCaRiA's proposal. Seeing only 5 other people besides myself have upvoted it, I worry it will get low priority 😟

**Comment by DutchPete** [comment]
Same as #315 ?

**Comment by MSBack** [comment]
I would also love to be able to embed the tables into notes, one way or the other.

**Comment by trey-wallis** [comment]
@SPiCaRiA Thank you for this analysis. I agree that having an embeddable table would be of great benefit to everyone in the community.

It's true the reason that I moved from an embedded markdown format to JSON because of technical constraints in Obsidian. The main issue is that the div container of the view that the table was rendered in would  be removed and then re-added very quickly. This caused a lot of lag with React and visible flashing. Reach is not meant to be unmounted and remounted in this manner. This also caused some data corruption issues, where I couldn't guarantee that saving would execute at the time that I expected it to.

I think an `immutable` dataview-ish solution is a good way to go. I assume, something like is what you are describing:

```nlt
table-123456
```
A codeblock with some type of identifier for this plugin e.g. `nlt` and then a table-id value.
Where `table-123456` is an id that can be copied via command or button from a table page.

**Comment by trey-wallis** [comment]
@elijah-scott @jaydeland @seanmcardwell @michaelhettmer jomenxiao @jasoncrevier Added in 6.14.0 :)

Please read these links to get started
- https://trey-wallis.github.io/obsidian-notion-like-tables/#/quickstart?id=linking-table-files
- https://trey-wallis.github.io/obsidian-notion-like-tables/#/embedding-tables

**Comment by DutchPete** [comment]
Following your instruction from this page (https://trey-wallis.github.io/obsidian-notion-like-tables/#/embedding-tables) I get no embedded file, as this shows

![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/10794265/440d6699-63c3-468e-b207-a0defc735478)
