### ISSUE TITLE
Go to next cell with keyboard

### ISSUE THREAD

**Issue by imeed166** [trey-wallis/obsidian-notion-like-tables#35]
**Is your feature request related to a problem? Please describe.**
Whenever I want to edit the next cell in the next column, I have to select it with the mouse.

**Describe the solution you'd like**
Create a keyboard shortcut to switch focus to the next cell (for example, enter twice or tab)

**Comment by trey-wallis** [comment]
@imeed166 I just published a basic version of this. Check it out in 2.3.0! Looking for feedback.

**Comment by imeed166** [comment]
When I press tab, it highlights the next cell, but I can't write in it until I select the cell.

https://user-images.githubusercontent.com/38974541/166098566-d4a75805-198b-4adc-a18c-fd3e0c1a4bca.mov

**Comment by trey-wallis** [comment]
@imeed166 It appears that Notion acts the same way. You press tab to focus the cell and then if you want to enter if you press enter.

**Comment by trey-wallis** [comment]
I can add it though. Would this be just for cells or headers as well?

**Comment by imeed166** [comment]
I use it mainly for cells, when it comes to headers, I don't use the keyboard that much.

**Comment by trey-wallis** [comment]
@imeed166 I just added it in 2.3.5. Check it out!

**Comment by trey-wallis** [comment]
Although, I am seeing now that if I want to implement the ability to move the focus around with arrow keys, and shift + tab (to go backwards), this might not be the best solution. I will keep it for right now though. I will have to figure out how to make a system for tabbing.

**Comment by imeed166** [comment]
It loses focus after pressing tab

https://user-images.githubusercontent.com/38974541/166132306-2a1dc0cf-5878-49d9-ae71-a22ed7858d84.mov

**Comment by trey-wallis** [comment]
That's not the behavior that I am receiving. Could you do cmd+p and send me your `Show debug info`?

**Comment by imeed166** [comment]
> Alternatively, I could do something like cmd + arrow keys for tabbing. Which do you think is easier to use/more accessible?

I don't think tabbing is used frequently in tables, but yeah this alternative is good enough I think.

> That's not the behavior that I am receiving. Could you do `cmd+p` and send me your `Show debug info`?

SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.5
	Operating system: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 21.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 30
	Safe mode: off
	Plugins installed: 63
	Plugins enabled: 60
		1: Divide & Conquer
		2: Better Word Count
		3: Buttons
		4: Creases
		5: Customizable Page Header and Title Bar
		6: Find unlinked files and unresolved links
		7: Format Hotkeys
		8: Hotkey Helper
		9: Media Extended
		10: MetaEdit
		11: MySnippets
		12: Natural Language Dates
		13: Number Headings
		14: Auto Link Title
		15: Banners
		16: Collapse All
		17: Custom Frames
		18: Emoji Toolbar
		19: File Cleaner
		20: Global Hotkeys
		21: Icon Shortcodes
		22: Imgur Plugin
		23: Kanban
		24: Linter
		25: Outliner
		26: Pandoc Plugin
		27: Reminder
		28: Shell commands
		29: Smart Typography
		30: Smarter Markdown Hotkeys
		31: Snippetor
		32: Style Settings
		33: System Dark Mode
		34: Tasks
		35: Version History Diff
		36: Pane Relief
		37: Plugin Changelogs
		38: QuickAdd
		39: Remotely Save
		40: Supercharged Links
		41: Advanced Tables
		42: Tabout
		43: Templater
		44: URI Commands
		45: Force note view mode
		46: Hider
		47: Add links to current note
		48: Full Calendar
		49: Snippet Commands
		50: Obsidian42 - BRAT
		51: Settings Search
		52: Obsius Publish
		53: Advanced URI
		54: Obsidian Badge
		55: Dataview
		56: Task Collector (TC)
		57: Obsidian Columns
		58: Multi-Column Markdown
		59: Dynamic Table of Contents
		60: Notion-Like Tables

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by trey-wallis** [comment]
@imeed166 Hmmmmm. I have the exact same versions as you. However, your OS is slightly newer than mine. Do you use a MacBook Air? That shouldn't matter though. I believe that there is another plugin interfering with things. I have no other plugins enabled but mine. Could you turn off all plugins except mine, restart Obsidian (to be safe) and try again?

**Comment by trey-wallis** [comment]
@imeed166 Actually. I do have buggish behavior. Ugh, sorry. I thought it would be a quick fix.

**Comment by trey-wallis** [comment]
@imeed166 Fixed in 2.3.5. Check it out!

**Comment by imeed166** [comment]
fixed, thanks.

**Comment by javiavid** [comment]
> It loses focus after pressing tab
> 
>  Screen.Recording.2022-05-01.at.5.30.50.AM.mov

I have the same problem with clean vault.

SYSTEM INFO:
	Obsidian version: v0.14.10
	Installer version: v0.14.5
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 2
	Safe mode: off
	Plugins installed: 16
	Plugins enabled: 1
		1: Notion-Like Tables

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by lveillard** [comment]
Hello, first of all, amazing plugin!

I'm facing thi same issue in windows 10. When I edit a cell, i press enter and then tab, the event is not captured by NLT, but I go to the sidebard instead 

Also not related but for some reason my tags are unreadable
![image](https://user-images.githubusercontent.com/29461076/187021390-798f8dba-8665-42d3-b2a5-21ce08707017.png)
