### ISSUE TITLE
Empty page in mobile iOS app

### ISSUE THREAD

**Issue by FinnRG** [trey-wallis/obsidian-notion-like-tables#364]
### Describe the bug

When I ue the iOS obsidian app and the plugin, every table is just an empty page.

![image](https://user-images.githubusercontent.com/65015656/232863504-1ab96abf-f78c-4335-abb1-e8018dd03e1f.jpeg)

### Steps to reproduce

1. Create a table with obsidian desktop
2. Open the file with obsidian iOS

### Expected behavior

Showing the table.

### Are you using the mobile app?

Yes

### Obsidian debug info

```

SYSTEM INFO:
	Operating system: ios 15.7.3 (Apple iPhone)
	Obsidian version: 1.4.3 (95)
	API version: v1.1.16
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Remotely Save v0.3.25
		2: Notion-Like Tables v6.3.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.


```

### Relevant log output

I don't think that extracting log information on iOS is possible.

**Comment by trey-wallis** [comment]
@FinnRG Thanks for submitting this. Resolved in 6.3.3. The UI for mobile is not perfect, as I have not done development for mobile. Everything seems to be working, besides drag and drop columns, drag and drop rows, and resizing columns. I will have to fix those out. If you discover any other issues on mobile, please make another bug issue. Cheers! :)
