### ISSUE TITLE
Date -> Text shows nothing

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-notion-like-tables#372]
### Describe the bug

If you have a date cell and change it to text, it doesn't show anything

### Steps to reproduce

1. Set a column to type `Date`
2. Add a date to one cell
3. Change the column to type `Text`

### Expected behavior

The text cell should render the date

### Are you using the mobile app?

No

### Obsidian debug info

N/A

**Comment by astevens2136** [comment]
I just installed this plugin for the first time and I can't get the date field to work at all. No matter what option I select, I either can't type in the box at all or if I can type, it doesn't save what I put. I've tried all the different date options and can't get any of them to work.

**Comment by trey-wallis** [comment]
Hi @astevens2136. Could I get a video/screenshot?

**Comment by astevens2136** [comment]
@trey-wallis It appears to be working now. I believe it may have been my theme interfering previously. I had some other odd things going on and ultimately switched themes and now everything works. :)
