### ISSUE TITLE
Can't drag columns or rows on mobile

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-notion-like-tables#379]
### Describe the bug

A user can't drag columns or rows on mobile.

### Steps to reproduce

Try to drag a row or column

### Expected behavior

The row should be draggable like desktop

### Are you using the mobile app?

No

### Obsidian debug info

N/A

**Comment by Moltastro** [comment]
Sadly encountering the same issue

**Comment by MSBack** [comment]
I am able to drag and drop on mobile sometimes, but it is very unreliable. But I think it is almost the same on desktop, so I'm not sure mobile is the issue.

**Comment by trey-wallis** [comment]
@MSBack This is related to #460. Please only use the drag icon for the row

**Comment by trey-wallis** [comment]
@Moltastro @MSBack Fixed in 6.10.0
