### ISSUE TITLE
New lines are hidden when table is filtered

### ISSUE THREAD

**Issue by clshafer** [trey-wallis/obsidian-notion-like-tables#387]
### Describe the bug

Searching for text filters the table display. If I then add a new row the empty row is not visible (because it does not contain the text that is being searched for)

Ideally I should be able to add new items to a filtered view.

### Steps to reproduce

1. Filter table using search
2. Select New Row

### Expected behavior

New, empty row should be displayed below the filtered view of the table

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.2.5
	Installer version: v1.1.16
	Operating system: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 22.3.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.1.2
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 26
	Plugins enabled: 24
		1: Excalidraw v1.8.26
		2: Kanban v1.5.2
		3: Advanced Tables v0.18.1
		4: Show Current File Path v0.5.2
		5: Calendar v1.5.10
		6: Dataview v0.5.55
		7: Periodic Notes v0.0.17
		8: Enhance Copy Note v0.2.1
		9: Style Settings v1.0.3
		10: Minimal Theme Settings v6.3.1
		11: Find orphaned files and broken links v1.9.0
		12: Customizable Page Header and Title Bar v4.7.2
		13: Contextual Typography v2.2.4
		14: QuickAdd v0.23.0
		15: Templater v1.16.0
		16: Natural Language Dates v0.6.1
		17: Buttons v0.4.19
		18: Creases v0.6.6
		19: Tasks v3.4.0
		20: ReadItLater v0.2.0
		21: Tag Wrangler v0.5.8
		22: Notion-Like Tables v6.5.0
		23: File Order v0.0.4
		24: Pandoc Plugin v0.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@clshafer If a filtered view were added, would you still want empty lines to appear if you were using the search bar?

**Comment by clshafer** [comment]
Yes. I use an excel spreadsheet to manage my todo list and one of the columns contains project. I will filter the master list by project, then add additional items to that project list.

**Comment by trey-wallis** [comment]
@clshafer Please try 6.8.0. I have implemented basic filtering on the `text`, `tag`, `multi-tag` and `checkbox` types. If a cell for a column that is being filtered is empty, the row will still appear. However, the search feature will filter all rows based on the search condition, even empty ones.

**Comment by clshafer** [comment]
What I'd like to be able to do is filter the table, then add a new row with the filter still applied. Currently when the table is filtered and I select new row, the new row is hidden COn May 8, 2023, at 2:38 PM, Trey Wallis ***@***.***> wrote:﻿
@clshafer Please try 6.8.0. I have implemented basic filtering on the text, tag, multi-tag and checkbox types. If a cell for a column that is being filtered is empty, the row will still appear. However, the search feature will filter all rows based on the search condition, even empty ones.

**Comment by trey-wallis** [comment]
@clshafer This must be a bug then. Can you post a screenshot of your filters + your search bar?

**Comment by trey-wallis** [comment]
@clshafer I found the issue. I apologize. Fixed in 6.9.3

**Comment by trey-wallis** [comment]
@clshafer Great! I'm glad to hear it's working. I have made search not keep empty rows. I think the search bar shouldn't show them because a search is a temporary filter that is used to find a very specific row. This is unlike a filter rule which is used to filter the row for long time as you add and delete items.
