### ISSUE TITLE
[Suggestion] Add a Filter to Columns

### ISSUE THREAD

**Issue by WilfredGuan** [trey-wallis/obsidian-notion-like-tables#388]
### Problem

Hi! Thank you so much about this wonderful add-on!

I really need this because Obsidian is kinda too 'heavy' for me to manage task flows, however, I find it's a little bit inconvenient in multi-task management. I can't quickly sort the tasks I need to focus.

### Solution

Here I'm wondering if you could add a simple filter to all columns, or maybe a dataview-like function?

For example, list all rows with the tag(s) selected only. It's vital in managing multiple project.

Thank you again for your add-on!

**Comment by trey-wallis** [comment]
@WilfredGuan I added a filtering system in 6.8.0. Please check it out! :)
