### ISSUE TITLE
Can't paste table in the note

### ISSUE THREAD

**Issue by m-hrachov** [trey-wallis/obsidian-notion-like-tables#421]
### Describe the bug

Hello! 
I used to have a table in one of my notes rendered using this code:

```notion-like-tables
table-id-i26TmG
```

After the update of Obsidian (and all the plugins), it stays like a code block and doesn't render.
When I try to create a new table, it opens in a new window. This is a very new behavior for me.

Tried to disable snippets and other plugins - didn't help.

Thank you in advance

### Steps to reproduce

Ctrl + P, "Notion-like tables: create table". 

### Expected behavior

Rendering of a table in the note.

Some text...
```notion-like-tables
table-id-i26TmG
```
Some other text...

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.2.7
	Installer version: v0.15.8
	Operating system: Windows 10 Home 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 7
		1: Notion-Like Tables v6.8.2
		2: Advanced Tables v0.18.1
		3: Better Word Count v0.9.6
		4: CodeMirror Options v0.9.5
		5: Editing Toolbar v2.3.1
		6: File Color v1.0.3
		7: Regex Find/Replace v1.2.0

**Comment by trey-wallis** [comment]
Hi @m-hrachov. Going from release 5.x to 6.x is a breaking change. The way tables are handled are now in their own separate file instead of in a markdown note. I am sorry if this is an inconvenience to you. You will have to remake your tables in the new format.
