### ISSUE TITLE
Cursor jumps to the end whenever the column name is edited and not at the end

### ISSUE THREAD

**Issue by GuybrushX** [trey-wallis/obsidian-notion-like-tables#424]
### Describe the bug

The cursor always jumps to the end of the column name when it is edited.

### Steps to reproduce

Try to rename a column and place the cursor anywhere but not at the end. For example try to change the name like that:
Before: My Column
After: This is My New Column

As soon as you place the cursor at the beginning or anywhere else the cursor jumps to the end.

Workarounds:
1. Write the new name somewhere else and paste it
2. Delete the column name and write it again from scratch

### Expected behavior

No jumping cursor.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.2.7
	Installer version: v1.2.7
	Operating system: Windows 10 Pro 10.0.22621 <- this seems to be an Obsidian bug, it's Win 11 Pro
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 10
		1: Obsidian Git v2.19.1
		2: Calendar v1.5.10
		3: Tasks v3.5.0
		4: Dataview v0.5.55
		5: Excalidraw v1.8.26
		6: ExcaliBrain v0.1.13
		7: Kanban v1.5.3
		8: Natural Language Dates v0.6.1
		9: Advanced Tables v0.18.1
		10: Notion-Like Tables v6.8.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Relevant log output

```shell
Shortcut doesn't work?
```

**Comment by trey-wallis** [comment]
@GuybrushX Thanks for finding this. I will push out the fix shortly

**Comment by trey-wallis** [comment]
@GuybrushX Fixed in 6.9.0

**Comment by GuybrushX** [comment]
@trey-wallis Thanks for the fast fix - unfortunately it doesn't work (anymore?). I'm using 6.9.1 already, didn't try 6.9.0. Behavior seems like before -> cursor is jumping to the end on each key press.

ESC key should also cancel and revert editing - that's another small issue but if you're on it maybe it's easy as well.

**Comment by trey-wallis** [comment]
@GuybrushX Which cell types is this happening for?

**Comment by GuybrushX** [comment]
I've checked Text, Checkbox, Number, all the same issue.

**Comment by trey-wallis** [comment]
@GuybrushX Could you record a video and post it here?

**Comment by trey-wallis** [comment]
@GuybrushX "ESC key should also cancel and revert editing - that's another small issue but if you're on it maybe it's easy as well." This is not how Notion currently works, I could add that as a feature though it if seems useful.

**Comment by trey-wallis** [comment]
@GuybrushX I apologize, I seem to have misread the issue with this post. I fixed this issue for all cell types but not the "column name". I will push out a fix shortly

**Comment by trey-wallis** [comment]
@GuybrushX Fixed in 6.9.3
