### ISSUE TITLE
Negative number/currency values are not supported/displayed

### ISSUE THREAD

**Issue by SPFxAppDev** [trey-wallis/obsidian-notion-like-tables#426]
### Describe the bug

For a number, it is not possible to enter negative numbers such as -120. The "-" is removed after the input. In a currency field it is possible to enter a negative number, but it is only displayed in "edit mode". In the display mode it looks like the field is empty. But in the "SUM" field it is ok. If you change the regex from [here](https://github.com/trey-wallis/obsidian-notion-like-tables/blob/master/src/shared/regex.ts#L6) as follows: 

```TypeScript
export const NUMBER_REGEX = new RegExp(/^-?\d+\.?\d*$/); 
```

the bug should be fixed 

### Steps to reproduce

Enter a negative field in a number or currency field. For example: -120

### Expected behavior

Negative numbers and currency values should be possible

### Are you using the mobile app?

Yes

### Obsidian debug info

Not needed

**Comment by trey-wallis** [comment]
@SPFxAppDev Thanks for that regex! I will push out the fix today along with the undo system :)

**Comment by trey-wallis** [comment]
@SPFxAppDev Fixed in 6.9.0
