### ISSUE TITLE
Column reordering is very unintuitive

### ISSUE THREAD

**Issue by GuybrushX** [trey-wallis/obsidian-notion-like-tables#434]
### Describe the bug

When you drag and drop columns to reorder them the new order is totally different to everything you're used to.

### Steps to reproduce

- Create a table with 5 columns
- Drag column 2 between column 4 + 5
- Column 2 will now become column 4 and column 4 will become column 2

### Expected behavior

- Column 2 should be between column 4 + 5 and become column 4
- Column 4 + 3 should move to column 3 + 2 respectively

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.2.8
	Installer version: v1.2.7
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 10
		1: Obsidian Git v2.19.1
		2: Calendar v1.5.10
		3: Tasks v3.7.0
		4: Dataview v0.5.55
		5: Excalidraw v1.9.1
		6: ExcaliBrain v0.1.13
		7: Kanban v1.5.3
		8: Natural Language Dates v0.6.1
		9: Advanced Tables v0.18.1
		10: Notion-Like Tables v6.9.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by GuybrushX** [comment]
@trey-wallis Just tested rows and yeah, I think it also should be changed. Excel and LibreOffice Calc and basically every other application I've ever used simply move the dragged column/row between the two columns/rows where you drop it.

**Comment by MSBack** [comment]
> @trey-wallis Just tested rows and yeah, I think it also should be changed. Excel and LibreOffice Calc and basically every other application I've ever used simply move the dragged column/row between the two columns/rows where you drop it.

I agree. I just came here to open an issue about the row reordering. The current behavior is completely unexpected and frustrating. I was trying to organize similar items, but with the current behavior, it's impossible. Relatedly, it would be nice to be able to insert columns and rows at the current location, so there is less need for dragging and dropping.

**Comment by trey-wallis** [comment]
@MSBack I am sorry for the frustration. I am pushing out a fix shortly. I have also made a new issue to insert above/insert below. Expect that to come out in the next few days. Cheers! :)

**Comment by MSBack** [comment]
Thanks man, I appreciate the responsiveness!

**Comment by trey-wallis** [comment]
@GuybrushX @MSBack Fixed in 6.9.3

**Comment by GuybrushX** [comment]
> @GuybrushX @MSBack Fixed in 6.9.3

Thanks a lot, that's much better and easier to work with! :-)
