### ISSUE TITLE
Table header color issues when using "Red Graphite" theme

### ISSUE THREAD

**Issue by AdrianSimionov** [trey-wallis/obsidian-notion-like-tables#435]
### Describe the bug

When "Red Graphite" theme is used, the colors this plugin is picking from the theme make the table headers a complete dark color, as seen in the screenshot.

On mouse-over the header cell is changing to the grey seen below. The other two columns, left and right, are without mouse-over effect.

<img width="551" alt="Screenshot 2023-05-18 at 2 02 21 pm" src="https://github.com/trey-wallis/obsidian-notion-like-tables/assets/6671693/4f7387b1-c7e6-44cd-bcc6-bdcdd1cf1246">

### Steps to reproduce

Install and enable "Red Graphite" theme.

### Expected behavior

The tables headers would use colors which would allow the header text to be visible.

### Are you using the mobile app?

No

### Obsidian debug info

N/A

**Comment by trey-wallis** [comment]
@AdrianSimionov Thanks for finding this.

**Comment by trey-wallis** [comment]
@AdrianSimionov Fixed in 6.9.3
