### ISSUE TITLE
Sorting does nothing on tag columns

### ISSUE THREAD

**Issue by MSBack** [trey-wallis/obsidian-notion-like-tables#437]
### Describe the bug

When I try to sort the table by a tag column (ascending or decending), nothing changes at all.

### Steps to reproduce

Try to sort a tag column in either the mobile app or on desktop.

### Expected behavior

I expected the rows to rearrange and get sorted, so the rows with the same tag are adjacent.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.2.8
	Installer version: v1.2.8
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 11
	Restricted mode: off
	Plugins installed: 105
	Plugins enabled: 91
		1: Divide & Conquer v1.0.0
		2: Advanced new file v1.5.1
		3: Advanced Slides v1.20.0
		4: Advanced URI v1.35.0
		5: Auto Link Title v1.4.1
		6: Banners v1.3.3
		7: Better Word Count v0.9.6
		8: Buttons v0.4.19
		9: Calendar v1.5.10
		10: Commander v0.5.0
		11: Custom Frames v2.4.6
		12: Dataview v0.5.56
		13: Dictionary v2.22.0
		14: Emoji Shortcodes v2.2.0
		15: Excalidraw v1.9.1
		16: Force note view mode v1.1.1
		17: Gallery v0.5.8
		18: Hide Sidebars on Window Resize v1.1.0
		19: Hotkey Helper v0.3.17
		20: Hotkeys++ v0.2.7
		21: Inbox v1.1.0
		22: Kanban v1.5.3
		23: LanguageTool Integration v0.3.3
		24: Natural Language Dates v0.6.1
		25: Note Refactor v1.7.1
		26: Obsidian42 - BRAT v0.7.0
		27: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		28: Obsidian42 - Text Transporter v1.0.3
		29: Pandoc Plugin v0.4.1
		30: Paste URL into selection v1.7.0
		31: Periodic Notes v0.0.17
		32: Prompt v1.1.0
		33: qmd as md v0.0.2
		34: Quick Explorer v0.2.8
		35: QuickAdd v1.0.1
		36: QuickShare v1.3.1
		37: Raindrop Highlights v0.0.17
		38: Reading Time v1.1.1
		39: Recent Files v1.3.5
		40: Review v1.6.4
		41: Smarter Markdown Hotkeys v1.16.4
		42: Sortable v0.3.1
		43: Spaced Repetition v1.10.1
		44: Style Settings v1.0.3
		45: Tag Wrangler v0.5.8
		46: Tasks v3.7.0
		47: Typewriter Scroll v0.2.2
		48: URI Commands v1.0.0
		49: Word Sprint v0.2.3
		50: Workbench v1.6.1
		51: Linter v1.14.0
		52: Update time on edit v1.1.2
		53: Templater v1.16.0
		54: Projects v1.15.3
		55: Cycle In Sidebar v1.0.2
		56: Emoji Toolbar v0.4.1
		57: Advanced Tables v0.18.1
		58: Table Enhancer v0.5.10
		59: Hover Editor v0.11.11
		60: Pandoc Reference List v1.2.11
		61: Create Note in Folder v0.0.9
		62: Plugin Groups v2.1.0
		63: Homepage v3.0.2
		64: Simple Day Planner v0.2.0
		65: Numerals v1.2.1
		66: Open vault in VSCode v1.2.1
		67: D2 v1.1.3
		68: Zotero Plugin v1.0.5
		69: Plugin Update Tracker v1.4.6
		70: Reminder v1.1.15
		71: File Diff v1.0.13
		72: Rollover Daily Todos v1.1.5
		73: Completr v3.1.3
		74: MetaEdit v1.8.0
		75: Gemmy v0.0.3
		76: Colorful Note Borders v0.2.4
		77: Supercharged Links v0.9.7
		78: Editor Syntax Highlight v0.1.3
		79: File Explorer Note Count v1.2.0
		80: Quiet Outline v0.3.15
		81: Readwise Official v2.0.1
		82: Enhancing Mindmap v0.2.4
		83: Home tab v1.1.2
		84: Obsidian Git v2.20.0
		85: Focus Mode v1.11.4
		86: Outliner v4.7.1
		87: Notion-Like Tables v6.9.1
		88: Settings Search v1.3.7
		89: Lapel v0.1.1
		90: Text Format v2.2.1
		91: Zotero Integration v2.3.9

**Comment by trey-wallis** [comment]
@MSBack Fixed in 6.10.0
