### ISSUE TITLE
[Question] How do I change via snippet.css the backgrond color of the table header?

### ISSUE THREAD

**Issue by BobWs** [trey-wallis/obsidian-notion-like-tables#453]
### Describe the bug

I'm sorry to ask, but how do I change the background color of the table headers and the cell text color via snippet.css?
Could you give me an example or point me in the right direction?
TIA

### Steps to reproduce

none

### Expected behavior

none

### Are you using the mobile app?

Yes

### Obsidian debug info

none

**Comment by trey-wallis** [comment]
@BobWs Hi Bob. The selector you would use would be 

```css
.NLT__app th {
   background-color: <your-color-here>
}
```

Would it be easier if I were to add back a class name for the header? Like `.NLT__th`?

**Comment by trey-wallis** [comment]
See the "CSS Styling" section of the README for more selectors. https://github.com/trey-wallis/obsidian-notion-like-tables#css-styling

**Comment by trey-wallis** [comment]
@BobWs I have added some additional documentation. Please see: https://trey-wallis.github.io/obsidian-notion-like-tables/#/guide-snippet

**Comment by BobWs** [comment]
@trey-wallis Thank you! ☺️

**Comment by ksdavidc** [comment]
links dead...
