### ISSUE TITLE
Display images

### ISSUE THREAD

**Issue by icebruce** [trey-wallis/obsidian-notion-like-tables#457]
### Problem

Currently there is no option to display images (ie Image field type). It would be very useful to have a column where we can show images for visual representation

### Solution

Enable the option to display images from an external link or from within Obsidian (internal link).
Additional image options for "fill image" "fit image" or any sort of positioning adjustment would be nice to have as well.

### Additional details

For reference [Obsidian Projects](https://github.com/marcusolsson/obsidian-projects) plugin has a similar feature, in case it is something that can be leveraged or reused here.

Example:
![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/66655064/7c7a95da-d8c3-4294-8ce8-41b28608546d)

**Comment by trey-wallis** [comment]
@icebruce Thanks for the feature request. Currently, images will render, if you use an image tag. You can render anything that Obsidian is capable of rendering in markdown. But yes, there is no image cell type. That seems like it would be a good addition :)

**Comment by icebruce** [comment]
Super cool, I did not realize I can use the image tag, thanks!

**Comment by SubChange** [comment]
> @icebruce Thanks for the feature request. Currently, images will render, if you use an image tag. e.g `<img src="">` You can render anything that Obsidian is capable of rendering in markdown. But yes, there is no image cell type. That seems like it would be a good addition :)

If I want to display images by image tag ` <img src="">`  using a relative path, what is the root folder that I can quote? It seems that ` <img src="">`  only works when I using absolute path.

**Comment by trey-wallis** [comment]
@icebruce @SubChange Added full image support in 6.19.0 using the `Embed` cell.
