### ISSUE TITLE
Unable to add more than 5 rows on mobile

### ISSUE THREAD

**Issue by Compg** [trey-wallis/obsidian-notion-like-tables#458]
### Describe the bug

Unable to scroll to bottom of table and click new row button on obsidian mobile iOS. Scroll snaps back up to last row and button is unclickable.

### Steps to reproduce

Add more than 5 rows on IOS. When table fills full display, unable to scroll to bottom and add additional rows.

### Expected behavior

Able to click the button and add new row

### Are you using the mobile app?

Yes

### Obsidian debug info

N/A on iOS

**Comment by trey-wallis** [comment]
Hi @Compg. I will place this as my next item to work on. I am working on another bug fix first.

**Comment by trey-wallis** [comment]
@Compg What is your screen size and which theme are you using? I am pushing out a fix that will work for my phone, but it seems like I am rendering more rows than you.

**Comment by trey-wallis** [comment]
@Compg Fixed in 6.10.0. I also did a lot of work for mobile. :)
