### ISSUE TITLE
Unable to drag and drop enteries beyond the 1st one

### ISSUE THREAD

**Issue by SaifEl-Deen** [trey-wallis/obsidian-notion-like-tables#460]
### Describe the bug

When I create a new table and try to drag and drop an entry, it works, draggin it or any other entry again doesn't work, I have to switch to another note/table/file and come back to it in order to be working again.

### Steps to reproduce

1. Create a table
2. Add multiple columns
3. Add multiple rows
4. Set the first column to date type
5. Create random date entries in the first column
6. Drag and drop any entry in the first column
7. Try to drag and drop any entry again, it won't work
8. Switch to another table/note/file and then come back, it will work again
![Animation](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/130001839/ed74b168-2e01-453a-8fbe-c566dfc5c480)

### Expected behavior

To be able to drag and drop beyond the 1st drag

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.2.8
	Installer version: v1.2.8
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Dynamic RTL v0.2.12
		2: Advanced Tables v0.18.1
		3: Calendar v1.5.10
		4: Kanban v1.5.3
		5: Notion-Like Tables v6.9.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Relevant log output

```shell
Ctrl-Alt-I Doesn't work
```

**Comment by trey-wallis** [comment]
@SaifEl-Deen Thanks for your bug report. I will check this out soon. What were you trying to accomplish with `Ctrl-Alt-I`? Currently redo is not implemented for drag and drop. See: #454

**Comment by SaifEl-Deen** [comment]
@trey-wallis You're welcome! Well, the bug report template asked me about something like a log or so, and it told me to press that shortcut to get that log.

**Comment by SaifEl-Deen** [comment]
No problems :D
I don't know where to look for that log, it opens a menu just like Google Chrome Inspect menu
I updated the first post with a gif, it may help.

**Comment by trey-wallis** [comment]
@SaifEl-Deen Thanks for the gif image, it made this issue very easy to debug. So the way that Notion handles dragging, and the way that I intend to handle draggle for now, is that you can only drag rows by using the drag icon. This is because I may want to implement other dragging abilities within the table itself. See: #467 

The issue with the drag icon being on the far right is that you have to potentially scroll to the right to reorder your rows. I will change this so that the drag icon is on the left.

I may change it to be able to work with just dragging a row in the near future, if I decide that it doesn't hurt anything.

**Comment by MSBack** [comment]
> The issue is rather that that I made the row UI change to be draggable, when in reality it isn't, only the icon is. I have fixed this.

Thanks for the clarification! I will see how I fare with this in mind 👍

**Comment by SaifEl-Deen** [comment]
@trey-wallis You're more than welcome, I see, yeah as you mentioned at least the handle should be at the left side instead.

**Comment by trey-wallis** [comment]
@SaifEl-Deen @MSBack Row drag button is now on the left side in 6.10.0 :)

**Comment by SaifEl-Deen** [comment]
@trey-wallis Thank you so much, that was actually fast, much appreciated 🤍
