### ISSUE TITLE
Can't link to a Notion-Like table from an Obsidian page

### ISSUE THREAD

**Issue by TimothyMRead** [trey-wallis/obsidian-notion-like-tables#461]
### Describe the bug

I can generate a Notion-Like table and it appears in the folder, as a table, but I can't link to it from an Obsidian page, when I type [[ it doesn't appear in the list.

### Steps to reproduce

Described above.

### Expected behavior

It should be possible to link to a table from any page within Obsidian using [[LINK_TO_TABLE]]

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.2
	Installer version: v1.1.16
	Operating system: Darwin Kernel Version 20.6.0: Thu Mar  9 20:39:26 PST 2023; root:xnu-7195.141.49.700.6~1/RELEASE_X86_64 20.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 19
	Plugins enabled: 19
		1: Paste URL into selection v1.7.0
		2: Periodic Notes v0.0.17
		3: Templater v1.16.0
		4: Natural Language Dates v0.6.1
		5: Outliner v4.4.0
		6: Janitor v1.0.7
		7: Local REST API v1.5.2
		8: Extract Highlights v0.0.18
		9: Advanced Tables v0.18.1
		10: Pandoc Plugin v0.4.1
		11: Webpage HTML Export v1.4.1
		12: Dataview v0.5.55
		13: QuickAdd v0.23.0
		14: Tasks v3.5.0
		15: Calendar v1.5.10
		16: Timestamp Notes v1.0.8
		17: Lumberjack 🪓 🪵 v1.3.0
		18: Omnivore v1.3.0
		19: Notion-Like Tables v6.9.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by salmanvol** [comment]
same issue for me as well

**Comment by TimothyMRead** [comment]
Well, I've found a work around. The problem is that the Norton-Like table is stored in a .table file and not a .md file, hence, Obsidian can't see it to link it automatically. However, if you know the name of the file, you can enter it manually, and it will link perfectly. E.g., if I have a table called Foo.table, then you link it from a page like: [[Foo.table]]. The path to the file with the table doesn't need to be added.

**Comment by Sirtz** [comment]
I mean that works, but what is the point of a table if I can't embed it into a file? That's pretty useless I feel like. It looks like to me: 
![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/26656736/26e64318-b8b0-47b4-8478-e89842dc2b27)

**Comment by mvrai** [comment]
I would also like to be able to link the table to the note. This allows you to add a description to the table, for example, and therefore it is easier to analyze.

**Comment by sebastianhuus** [comment]
Just started using the plugin for the first time and got the same problem

**Comment by MSBack** [comment]
> I mean that works, but what is the point of a table if I can't embed it into a file? That's pretty useless I feel like.

First, it's certainly not useless. It is very useful to organize information in the NLT, even though it's currently not possible to embed the table. Secondly, it's not a bug as labelled here, but a desired feature, which I might add, has already been requested [here](https://github.com/trey-wallis/obsidian-notion-like-tables/issues/322) and [here](https://github.com/trey-wallis/obsidian-notion-like-tables/issues/345). Second issue has more discussion, so check that out.

Embedding tables into markdown notes is listed as up next on the Roadmap: https://github.com/users/trey-wallis/projects/2

Development of requested features has been very rapid lately, so you should just be patient.

**Comment by trey-wallis** [comment]
@TimothyMRead I just added documentation about making the table appear in the file suggest menu. You need to enable `detect all extensions` in the settings menu. Please see: https://github.com/trey-wallis/obsidian-notion-like-tables#linking-table-files

**Comment by trey-wallis** [comment]
> I mean that works, but what is the point of a table if I can't embed it into a file? That's pretty useless I feel like. It looks like to me: ![image](https://user-images.githubusercontent.com/26656736/240332263-26e64318-b8b0-47b4-8478-e89842dc2b27.png)

This is the same behavior as canvas.

**Comment by TimothyMRead** [comment]
> @TimothyMRead I just added documentation about making the table appear in the file suggest menu. You need to enable `detect all extensions` in the settings menu. Please see: https://github.com/trey-wallis/obsidian-notion-like-tables#linking-table-files

Thanks. That is really useful. Something else I have just learnt. It's a really great plugin BTW!

**Comment by trey-wallis** [comment]
@TimothyMRead  @Sirtz @salmanvol @sebastianhuus Added in 6.14.0 :)

Please read these links to get started
- https://trey-wallis.github.io/obsidian-notion-like-tables/#/quickstart?id=linking-table-files
- https://trey-wallis.github.io/obsidian-notion-like-tables/#/embedding-tables

**Comment by salmanvol** [comment]
Hi,

thanks very much for the update, works just as expected.

One more thing, is there any way to resize the size of the embedded file?, I see for an image you can do    
![[image.png|300x300]] but this doesn't seem to work for the .table files. This is an issue for me as I have to scroll a lot to see all the rows and columns in my table

Thanks again for all your work.

**Comment by MSBack** [comment]
> One more thing, is there any way to resize the size of the embedded file?, I see for an image you can do    
> ![[image.png|300x300]] but this doesn't seem to work for the .table files. This is an issue for me as I have to scroll a lot to see all the rows and columns in my table

I too would love to resize the table to increase the height. The standard height is a bit too small for tables with many rows. I see Trey already made an issue about height adjustment.

**Comment by Sirtz** [comment]
I just tried it today, works amazingly thank you so so much!
