### ISSUE TITLE
Roadmap .... and escape hatch

### ISSUE THREAD

**Issue by lymeswold** [trey-wallis/obsidian-notion-like-tables#466]
### Problem

Would love to see a rough roadmap for enhancements to this plugin.

### Solution

And for those of us who are using it now - with some trepidation because of the lack of certain key features - it would be useful to have a way of dumping the entire contents of a NLT to a plain-text file (CSV or similar), so we have an escape route.

**Comment by trey-wallis** [comment]
@lymeswold Roadmap is here: https://github.com/users/trey-wallis/projects/2. I just added a TON of bug fixes. Next up will be CSV import/export.

**Comment by lymeswold** [comment]
Brilliant, thanks. Enjoying using this great plugin.

**Comment by trey-wallis** [comment]
@lymeswold Added in 6.13.0
