### ISSUE TITLE
6.13.0 breaks mobile

### ISSUE THREAD

**Issue by Compg** [trey-wallis/obsidian-notion-like-tables#502]
### Describe the bug

Plug-in fails to load on iPhone and iPad after most recent update. Full uninstall, reboot, reinstall does not resolve

### Steps to reproduce

Described above

### Expected behavior

Plug-in loads

### Are you using the mobile app?

Yes

### Obsidian debug info

N/A for ios

**Comment by trey-wallis** [comment]
@Compg It appears that the library I'm using for csv processing uses `Buffer` which is not available on mobile.

**Comment by trey-wallis** [comment]
@Compg I have replaced the `csv-stringify` library with `papaparse`. Everything is working now. Sorry for the inconvenience.

**Comment by Compg** [comment]
@trey-wallis thanks for the quick fix! I’ve been recommending your plugin to all my colleagues. It’s only a matter of time until Obsidian team reachs out to collaborate and bundle this as a Core plugin.
