### ISSUE TITLE
Resizable embedded table

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-notion-like-tables#514]
### Problem

Currently the table has a fixed height, that means that if there's less rows, it will seem abnormally large, but if there's more rows that a user would like to view, they cannot.

### Solution

Make the embedded table container resizable.

**Comment by salmanvol** [comment]
just commenting here so I remember to stay up-to-date with this thread as this is the final major hurdle for me with notion-like-tables

**Comment by trey-wallis** [comment]
@salmanvol @msback Added in 6.15.0

**Comment by csss1234** [comment]
Can you help me figure out how to resize the embed? Mine seems stuck at just 4-5 rows
