### ISSUE TITLE
do not support tag

### ISSUE THREAD

**Issue by juestchaos** [trey-wallis/obsidian-notion-like-tables#52]
Thanks for this great plug-in and work.

Firtst,Can't use type: tag，e.g. #day/birthday or #day-birthday . it will be show：Invalid data. Expected type: tag

Secondy,tag  Can't be used emoji like #⭐⭐⭐⭐⭐ . it Will be displayed as a blank both edit mode and preview mode.

**Comment by trey-wallis** [comment]
Hi @juestchaos. I will look into these. Thanks for posting

**Comment by trey-wallis** [comment]
@juestchaos These tags are working in 1.0.0. Check it out!

**Comment by juestchaos** [comment]
Well done!
Database is a great idea for NOTION.
Such migration work may be like DataView to OBSIDIAN.

I tested the compatibility problem of type:tag  in version 1.2.Everything is just peachy.

**Comment by trey-wallis** [comment]
@juestchaos I didn't understand what you meant about databases. Are you talking about the Obsidian plugin Dataview or the Notion databases view?
