### ISSUE TITLE
Inability to select, create, or apply multi tags

### ISSUE THREAD

**Issue by Compg** [trey-wallis/obsidian-notion-like-tables#540]
### Describe the bug

Unable to select or add to tag drop down list on 6.17.0 on mobile

### Steps to reproduce

Add new row. Attempt to apply 1-n tag values. Tag remains highlighted and is not applied

### Expected behavior

Application of tag

### Are you using the mobile app?

Yes

### Obsidian debug info

NA

**Comment by trey-wallis** [comment]
@Compg I have fixed this. I will push out the fix tomorrow

**Comment by trey-wallis** [comment]
@Compg Fixed in 6.18.0
