### ISSUE TITLE
no puedo abrir las tablas 

### ISSUE THREAD

**Issue by josniel** [trey-wallis/obsidian-notion-like-tables#542]
### Describe the bug

al bajar la ultima actualizacion me da un error al intentar abrir mis archivos tabla
 este es el error
var CellIdError = class extends Error {
  constructor(id2) {
    super(`Reference cell ${id2} is undefined`);
    this.name = "CellIdError";
  }
};

![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/69477664/71488244-0e23-4dac-bafb-6cec9ce6268f)

### Steps to reproduce

al intentar abrir un archivo cualquiera de los ya creados luego de la ultima actualización

### Expected behavior

abrir mi archivo

### Are you using the mobile app?

No

### Obsidian debug info

![image](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/69477664/b8cca2b2-5d6f-489f-a571-41e7cdc4d6cd)

**Comment by trey-wallis** [comment]
@josniel Hola. Lamento que esto este pasando. Puede ser que este pasando a otras personas tambien. Me puedes checkar la version de los tables. Puedes abrir el archivo en otra app como un editor de texto  y ver la llave `pluginVersion`?

**Comment by trey-wallis** [comment]
Puedes poner el debug info tambien?

`Cmd-P` (Mac) o `Ctrl-P` (Windows). Search "Show debug info". Click "copy to clipboard."

**Comment by josniel** [comment]
@trey-wallis buen dia gracias por responder.  en el manifest.json veo esto
{
	"id": "notion-like-tables",
	"name": "Notion-Like Tables",
	"minAppVersion": "0.15.0",
	"description": "Your premiere tool for creating and managing tabular data in Obsidian.md",
	"author": "Trey Wallis",
	"authorUrl": "https://github.com/trey-wallis",
	"isDesktopOnly": false,
	"fundingUrl": "https://www.buymeacoffee.com/treywallis",
	"version": "6.17.0"
}
imagino que la version es: "6.17.0", por si sirve de algo estoy usando ubuntu 22.04 como sistema operativo

**Comment by trey-wallis** [comment]
No he probado el sistema en Ubuntu. Es posible que esto sea el problema. Me puedes mandar todos los datos de 1 archivo? Si no es algo muy personal.

**Comment by josniel** [comment]
si puedo compartir alguno, te lo envio como archivo.table o texto?

**Comment by josniel** [comment]
alli es donde realmente estaba la llave  "pluginVersion": 693

**Comment by trey-wallis** [comment]
Perfecto. Voy a poder encontrar el problema

**Comment by trey-wallis** [comment]
@josniel He encontrado el problema. Estoy trabajando en un nuevo build asi que he tardado un poco. Gracias por ser paciente. Voy a lanzar la nueva versión del software en la proxima hora.

**Comment by trey-wallis** [comment]
@josniel El problema debería ser resuelto. Avisame si todavia encuentras problemas. Gracias :)
