### ISSUE TITLE
Shift + Enter inside a cell doesn't work since last update

### ISSUE THREAD

**Issue by charle36** [trey-wallis/obsidian-notion-like-tables#550]
### Describe the bug

Unless I'm mistaken, we lost the ability to add lines inside a text cell since the last update. I think it's a useful feature and I hope it can be brought back.

### Steps to reproduce

Type something in a text cell, then press shift + enter.

### Expected behavior

Create a line above the previous one in the cell.

### Are you using the mobile app?

No

### Obsidian debug info

Not relevant

**Comment by trey-wallis** [comment]
@charle36 Fixed in 6.18.1

**Comment by charle36** [comment]
Thanks !
