### ISSUE TITLE
Results from Tasks query rendering center justified

### ISSUE THREAD

**Issue by clshafer** [trey-wallis/obsidian-notion-like-tables#567]
### Describe the bug

I've embedded a tasks plugin query in a cell - which is incredibly useful! For narrow width cells results display left-aligned, as they should, but the results are rendering center-justified when cell width is set wide. I'm using the Minimal theme and am on a Mac.

![Screenshot 2023-06-14 at 8 19 03 AM](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/96744897/8aee03dd-d991-4d63-b621-4db1a0281811)

![Screenshot 2023-06-14 at 8 09 13 AM](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/96744897/60875ee6-1257-4be6-95f4-8cd0e3591db5)

### Steps to reproduce

Embed a Tasks plugin query in a text cell. Use a fairly large amount of text for the task description. Resize width of cell to see alignment of task items move between left and center alignment.

### Expected behavior

Items should remain left justified, regardless of cell width

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.1.16
	Operating system: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 22.5.0
	Login status: logged in
	Catalyst license: vip
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.3.3
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 27
	Plugins enabled: 25
		1: Excalidraw v1.9.3
		2: Kanban v1.5.3
		3: Advanced Tables v0.18.1
		4: Show Current File Path v0.5.2
		5: Calendar v1.5.10
		6: Dataview v0.5.56
		7: Periodic Notes v0.0.17
		8: Enhance Copy Note v0.2.1
		9: Style Settings v1.0.6
		10: Minimal Theme Settings v6.3.1
		11: Find orphaned files and broken links v1.9.0
		12: Customizable Page Header and Title Bar v4.7.2
		13: Contextual Typography v2.2.5
		14: QuickAdd v1.0.2
		15: Templater v1.16.0
		16: Natural Language Dates v0.6.1
		17: Buttons v0.4.19
		18: Creases v0.6.6
		19: Tasks v3.10.0
		20: ReadItLater v0.3.0
		21: Tag Wrangler v0.5.11
		22: Pandoc Plugin v0.4.1
		23: Obsidian Enhancing Export v1.6.1
		24: Notion-Like Tables v6.18.6
		25: File Order v0.0.6

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@clshafer Thanks for the bug report. I will fix this today.
