### ISSUE TITLE
Feature request: Image inserting

### ISSUE THREAD

**Issue by adrikty** [trey-wallis/obsidian-notion-like-tables#572]
### Problem

Hello!
There's a limitation in the plugin which is inserting images, thumbnails. When I want to link an image (eg. [[tree.jpg]] from my vault, it makes it a link and there's no way to make a little preview. Usage: I'm making an offline music database.
Option to scale it to [[tree.jpg|50]] also doesn't work. especially when typing ![[tree.jpg|50]] which makes brackets a simple text.
[Source from the tutorial](https://notes.nicolevanderhoeven.com/obsidian-playbook/Using+Obsidian/02+Making+Notes+in+Obsidian/Attaching+images+to+Obsidian)

### Solution

Linking images from vault with fixed height based on row would be the best solution there (since this is a table), something like 50x50 px max. For example when I was inserting images in notion, various sizes (200x200, 50x50, irregular) were scaled to about 27x27 px. 

### Additional details

screenshots: (1. obsidian, 2. notion)
1. https://cdn.discordapp.com/attachments/1103715161413525565/1119017294526414848/image.png
2. https://cdn.discordapp.com/attachments/1103715161413525565/1119017568578064484/image.png

**Comment by trey-wallis** [comment]
Hi @adrikty. Thank you for your feature request. It is frustrating that the Obsidian `MarkdownRender.renderMarkdown` function doesn't render embedded image links. I will work on this next.

**Comment by trey-wallis** [comment]
Related to #457

**Comment by trey-wallis** [comment]
@adrikty Fixed in 6.19.0. Please use the `Embed` cell type when using embedding images
