### ISSUE TITLE
[Feature Request] Copy Content of the Cell

### ISSUE THREAD

**Issue by FelipeRearden** [trey-wallis/obsidian-notion-like-tables#64]
Hello @trey-wallis !!!!!

Fantastic idea !!!!!!!!! We really need someone to share some :heart: to Obsidian Tables :)

## My FR

Would be amazing if we could **Copy** the content of a Cell 

My suggestion is to use the right mouse click to copy the content to the clipboard. 
- If I right click a cell, the content will be copied to the clipboard :)

---

Thanks for reading this !!!!

Have a great day !!!!

**Comment by trey-wallis** [comment]
@FelipeRearden Added in 2.1.0. Check it out! :)

**Comment by FelipeRearden** [comment]
Hello @trey-wallis !!!!!

Thank you very much for this feature !!!!

Working perfect on Obsidian `0.14.6` version `2.3.1`

Forgive for my late reply, It's been a busy week 

Have a great day 🌞
