### ISSUE TITLE
[Feature Request] Render Markdown and HTML tags

### ISSUE THREAD

**Issue by FelipeRearden** [trey-wallis/obsidian-notion-like-tables#65]
Hello @trey-wallis !!!!

Would be amazing if we could render `**Bold**` `*Italic*` `==Highlights==` and HTML tags like `<u>Underline</u>` in Reading and Live Preview Modes :)

This way We could make our tables even more beautiful :)

---

Thanks for reading this !!!!

Have a great day!!!!!

**Comment by trey-wallis** [comment]
@FelipeRearden That is a great suggestion! I will look into adding this.

**Comment by FelipeRearden** [comment]
> @FelipeRearden That is a great suggestion! I will look into adding this.

Thanks you very much @trey-wallis !!!!

**Comment by trey-wallis** [comment]
@FelipeRearden I plan on adding this in the next release. :)

**Comment by FelipeRearden** [comment]
> @FelipeRearden I plan on adding this in the next release. :)

Thank you very much @trey-wallis !!!!!!

**Comment by trey-wallis** [comment]
@FelipeRearden Added in 3.4.0. Check it out! :)

**Comment by FelipeRearden** [comment]
> @FelipeRearden Added in 3.4.0. Check it out! :)

This is absolutely fantastic @trey-wallis !!!!

Working perfect on version `3.4.1` !!!!!

Thank you and have a great day 🌞
