### ISSUE TITLE
[BUG] Ascending/descending order is inverted compared to all other apps

### ISSUE THREAD

**Issue by KierPrev** [trey-wallis/obsidian-notion-like-tables#66]
When you use "descending", the column should be order from the higher value to the lower value, descending:
10
9
8
7
.....

And the opposite way for ascending.

**Comment by trey-wallis** [comment]
@KierPrev Thanks for catching this! I seem to have mixed things up

**Comment by trey-wallis** [comment]
Fixed in 2.0.1
