### ISSUE TITLE
Being able to change the color of the tags, at least from 8 basic colors.

### ISSUE THREAD

**Issue by KierPrev** [trey-wallis/obsidian-notion-like-tables#67]
The title speaks for itself.

**Comment by trey-wallis** [comment]
@KierPrev Yes, I have been wanting to this. The caching system took way longer than expected! I will get something out of the end of this week.

**Comment by trey-wallis** [comment]
@KierPrev I plan on doing this tomorrow in addition to adding checkbox + date types. Stay tuned :)

**Comment by trey-wallis** [comment]
@KierPrev @Sibiriak @juestchaos @ngirard @FelipeRearden Added in 3.2.0. Check it out! :)
