### ISSUE TITLE
Reorder rows and columns

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-notion-like-tables#80]
**Is your feature request related to a problem? Please describe.**
Reordering rows and columns is currently not possible.

**Describe the solution you'd like**
Move column left or right
Move row up or down

**Describe alternatives you've considered**
These buttons would be a good accessibility add on besides row/column dragging in the future

**Additional context**

**Comment by trey-wallis** [comment]
Added in 2.1.0

**Comment by imeed166** [comment]
Sorry to comment on a closed issue, but Is it on the roadmap to reorder rows and columns by dragging and dropping ?
