### ISSUE TITLE
Support Obsidian Internal Link in the NLT.

### ISSUE THREAD

**Issue by An-qi-Zhang** [trey-wallis/obsidian-notion-like-tables#86]
Thank you very much for this plugin!

I tried to update my tables with [[internal links]] into NLT, but the link cannot be clicked open in the preview mode.

It would be great if this plugin can support Obsidian internal links.

**Comment by trey-wallis** [comment]
@An-qi-Zhang Hi An-qi-Zhang. Thank you for your feedback! Hmm. Yes, it does appear not to be working. I will push out a fix shortly.
